package com.csot.gm.materialManage.dao.original.gmPartNoRuleMap;

import com.csot.gm.materialManage.model.original.gmPartNoRuleMap.GmPartNoRuleMap;
import com.csot.gm.materialManage.model.original.gmPartNoRuleMap.GmPartNoRuleMapCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface GmPartNoRuleMapMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  int countByExample(GmPartNoRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  int deleteByExample(GmPartNoRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  int insert(GmPartNoRuleMap record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  int insertSelective(GmPartNoRuleMap record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  List<GmPartNoRuleMap> selectByExample(GmPartNoRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  GmPartNoRuleMap selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") GmPartNoRuleMap record,
      @Param("example") GmPartNoRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") GmPartNoRuleMap record,
      @Param("example") GmPartNoRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(GmPartNoRuleMap record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE_MAP
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(GmPartNoRuleMap record);
}