package com.csot.gm.materialManage.dao.extension.flowNo;

import com.csot.gm.materialManage.model.extension.flowNo.FlowNoExtCriteria;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;

public interface FlowNoExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int countByExample(FlowNoExtCriteria example);
}