package com.csot.gm.materialManage.model.extension.propertyRtn;

import java.util.ArrayList;
import java.util.List;
import org.amberframework.core.mybatis.pojo.Page;

public class PropertyRtnExtCriteria {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  protected Page page;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public PropertyRtnExtCriteria() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public void setPage(Page page) {
    this.page = page;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public Page getPage() {
    return this.page;
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("ID is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("ID is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(String value) {
      addCriterion("ID =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(String value) {
      addCriterion("ID <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(String value) {
      addCriterion("ID >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(String value) {
      addCriterion("ID >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(String value) {
      addCriterion("ID <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(String value) {
      addCriterion("ID <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLike(String value) {
      addCriterion("ID like", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotLike(String value) {
      addCriterion("ID not like", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<String> values) {
      addCriterion("ID in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<String> values) {
      addCriterion("ID not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(String value1, String value2) {
      addCriterion("ID between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(String value1, String value2) {
      addCriterion("ID not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andCreateUidIsNull() {
      addCriterion("CREATE_UID is null");
      return (Criteria) this;
    }

    public Criteria andCreateUidIsNotNull() {
      addCriterion("CREATE_UID is not null");
      return (Criteria) this;
    }

    public Criteria andCreateUidEqualTo(String value) {
      addCriterion("CREATE_UID =", value, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidNotEqualTo(String value) {
      addCriterion("CREATE_UID <>", value, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidGreaterThan(String value) {
      addCriterion("CREATE_UID >", value, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidGreaterThanOrEqualTo(String value) {
      addCriterion("CREATE_UID >=", value, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidLessThan(String value) {
      addCriterion("CREATE_UID <", value, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidLessThanOrEqualTo(String value) {
      addCriterion("CREATE_UID <=", value, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidLike(String value) {
      addCriterion("CREATE_UID like", value, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidNotLike(String value) {
      addCriterion("CREATE_UID not like", value, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidIn(List<String> values) {
      addCriterion("CREATE_UID in", values, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidNotIn(List<String> values) {
      addCriterion("CREATE_UID not in", values, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidBetween(String value1, String value2) {
      addCriterion("CREATE_UID between", value1, value2, "createUid");
      return (Criteria) this;
    }

    public Criteria andCreateUidNotBetween(String value1, String value2) {
      addCriterion("CREATE_UID not between", value1, value2, "createUid");
      return (Criteria) this;
    }

    public Criteria andPropertyNameIsNull() {
      addCriterion("PROPERTY_NAME is null");
      return (Criteria) this;
    }

    public Criteria andPropertyNameIsNotNull() {
      addCriterion("PROPERTY_NAME is not null");
      return (Criteria) this;
    }

    public Criteria andPropertyNameEqualTo(String value) {
      addCriterion("PROPERTY_NAME =", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameNotEqualTo(String value) {
      addCriterion("PROPERTY_NAME <>", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameGreaterThan(String value) {
      addCriterion("PROPERTY_NAME >", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameGreaterThanOrEqualTo(String value) {
      addCriterion("PROPERTY_NAME >=", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameLessThan(String value) {
      addCriterion("PROPERTY_NAME <", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameLessThanOrEqualTo(String value) {
      addCriterion("PROPERTY_NAME <=", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameLike(String value) {
      addCriterion("PROPERTY_NAME like", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameNotLike(String value) {
      addCriterion("PROPERTY_NAME not like", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameIn(List<String> values) {
      addCriterion("PROPERTY_NAME in", values, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameNotIn(List<String> values) {
      addCriterion("PROPERTY_NAME not in", values, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameBetween(String value1, String value2) {
      addCriterion("PROPERTY_NAME between", value1, value2, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameNotBetween(String value1, String value2) {
      addCriterion("PROPERTY_NAME not between", value1, value2, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyTextIsNull() {
      addCriterion("PROPERTY_TEXT is null");
      return (Criteria) this;
    }

    public Criteria andPropertyTextIsNotNull() {
      addCriterion("PROPERTY_TEXT is not null");
      return (Criteria) this;
    }

    public Criteria andPropertyTextEqualTo(String value) {
      addCriterion("PROPERTY_TEXT =", value, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextNotEqualTo(String value) {
      addCriterion("PROPERTY_TEXT <>", value, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextGreaterThan(String value) {
      addCriterion("PROPERTY_TEXT >", value, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextGreaterThanOrEqualTo(String value) {
      addCriterion("PROPERTY_TEXT >=", value, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextLessThan(String value) {
      addCriterion("PROPERTY_TEXT <", value, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextLessThanOrEqualTo(String value) {
      addCriterion("PROPERTY_TEXT <=", value, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextLike(String value) {
      addCriterion("PROPERTY_TEXT like", value, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextNotLike(String value) {
      addCriterion("PROPERTY_TEXT not like", value, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextIn(List<String> values) {
      addCriterion("PROPERTY_TEXT in", values, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextNotIn(List<String> values) {
      addCriterion("PROPERTY_TEXT not in", values, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextBetween(String value1, String value2) {
      addCriterion("PROPERTY_TEXT between", value1, value2, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyTextNotBetween(String value1, String value2) {
      addCriterion("PROPERTY_TEXT not between", value1, value2, "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyValueIsNull() {
      addCriterion("PROPERTY_VALUE is null");
      return (Criteria) this;
    }

    public Criteria andPropertyValueIsNotNull() {
      addCriterion("PROPERTY_VALUE is not null");
      return (Criteria) this;
    }

    public Criteria andPropertyValueEqualTo(String value) {
      addCriterion("PROPERTY_VALUE =", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueNotEqualTo(String value) {
      addCriterion("PROPERTY_VALUE <>", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueGreaterThan(String value) {
      addCriterion("PROPERTY_VALUE >", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueGreaterThanOrEqualTo(String value) {
      addCriterion("PROPERTY_VALUE >=", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueLessThan(String value) {
      addCriterion("PROPERTY_VALUE <", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueLessThanOrEqualTo(String value) {
      addCriterion("PROPERTY_VALUE <=", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueLike(String value) {
      addCriterion("PROPERTY_VALUE like", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueNotLike(String value) {
      addCriterion("PROPERTY_VALUE not like", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueIn(List<String> values) {
      addCriterion("PROPERTY_VALUE in", values, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueNotIn(List<String> values) {
      addCriterion("PROPERTY_VALUE not in", values, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueBetween(String value1, String value2) {
      addCriterion("PROPERTY_VALUE between", value1, value2, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueNotBetween(String value1, String value2) {
      addCriterion("PROPERTY_VALUE not between", value1, value2, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andIdLikeInsensitive(String value) {
      addCriterion("upper(ID) like", value.toUpperCase(), "id");
      return (Criteria) this;
    }

    public Criteria andCreateUidLikeInsensitive(String value) {
      addCriterion("upper(CREATE_UID) like", value.toUpperCase(), "createUid");
      return (Criteria) this;
    }

    public Criteria andPropertyNameLikeInsensitive(String value) {
      addCriterion("upper(PROPERTY_NAME) like", value.toUpperCase(), "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyTextLikeInsensitive(String value) {
      addCriterion("upper(PROPERTY_TEXT) like", value.toUpperCase(), "propertyText");
      return (Criteria) this;
    }

    public Criteria andPropertyValueLikeInsensitive(String value) {
      addCriterion("upper(PROPERTY_VALUE) like", value.toUpperCase(), "propertyValue");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}