package com.csot.gm.materialManage.model.extension.flowNo;

import java.io.Serializable;

public class FlowNoExt implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FLOW_NO.PART_NUM
   *
   * @mbggenerated
   */
  private String partNum;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FLOW_NO.PART_FLOW_NUM
   *
   * @mbggenerated
   */
  private String partFlowNum;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FLOW_NO.PART_NUM
   *
   * @return the value of T_GM_FLOW_NO.PART_NUM
   *
   * @mbggenerated
   */
  public String getPartNum() {
    return partNum;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FLOW_NO.PART_NUM
   *
   * @param partNum the value for T_GM_FLOW_NO.PART_NUM
   *
   * @mbggenerated
   */
  public void setPartNum(String partNum) {
    this.partNum = partNum == null ? null : partNum.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FLOW_NO.PART_FLOW_NUM
   *
   * @return the value of T_GM_FLOW_NO.PART_FLOW_NUM
   *
   * @mbggenerated
   */
  public String getPartFlowNum() {
    return partFlowNum;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FLOW_NO.PART_FLOW_NUM
   *
   * @param partFlowNum the value for T_GM_FLOW_NO.PART_FLOW_NUM
   *
   * @mbggenerated
   */
  public void setPartFlowNum(String partFlowNum) {
    this.partFlowNum = partFlowNum == null ? null : partFlowNum.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    FlowNoExt other = (FlowNoExt) that;
    return (this.getPartNum() == null ? other.getPartNum() == null : this.getPartNum().equals(
        other.getPartNum()))
        && (this.getPartFlowNum() == null ? other.getPartFlowNum() == null : this.getPartFlowNum()
            .equals(other.getPartFlowNum()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getPartNum() == null) ? 0 : getPartNum().hashCode());
    result = prime * result + ((getPartFlowNum() == null) ? 0 : getPartFlowNum().hashCode());
    return result;
  }
}
