package com.csot.gm.materialManage.dao.original.userInfo;

import com.csot.gm.materialManage.model.original.userInfo.UserInfo;
import com.csot.gm.materialManage.model.original.userInfo.UserInfoCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  int countByExample(UserInfoCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  int deleteByExample(UserInfoCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  int insert(UserInfo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  int insertSelective(UserInfo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  List<UserInfo> selectByExample(UserInfoCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  UserInfo selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") UserInfo record,
      @Param("example") UserInfoCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(UserInfo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_USER_INFO
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(UserInfo record);
}
