package com.csot.gm.materialManage.dao.original.partNo;

import com.csot.gm.materialManage.model.original.partNo.PartNo;
import com.csot.gm.materialManage.model.original.partNo.PartNoCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PartNoMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  int countByExample(PartNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  int deleteByExample(PartNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  int insert(PartNo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  int insertSelective(PartNo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  List<PartNo> selectByExample(PartNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  PartNo selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") PartNo record,
      @Param("example") PartNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") PartNo record, @Param("example") PartNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(PartNo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(PartNo record);
}