package com.csot.gm.materialManage.model.extension.partType;

import java.io.Serializable;

public class PartTypeExt implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_TYPE.ID
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_TYPE.PART_TYPE_REAL_NAME
   *
   * @mbggenerated
   */
  private String partTypeRealName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_TYPE.PART_TYPE_DIS_NAME
   *
   * @mbggenerated
   */
  private String partTypeDisName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_TYPE.ID
   *
   * @return the value of T_GM_PART_TYPE.ID
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_TYPE.ID
   *
   * @param id the value for T_GM_PART_TYPE.ID
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_TYPE.PART_TYPE_REAL_NAME
   *
   * @return the value of T_GM_PART_TYPE.PART_TYPE_REAL_NAME
   *
   * @mbggenerated
   */
  public String getPartTypeRealName() {
    return partTypeRealName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_TYPE.PART_TYPE_REAL_NAME
   *
   * @param partTypeRealName the value for T_GM_PART_TYPE.PART_TYPE_REAL_NAME
   *
   * @mbggenerated
   */
  public void setPartTypeRealName(String partTypeRealName) {
    this.partTypeRealName = partTypeRealName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_TYPE.PART_TYPE_DIS_NAME
   *
   * @return the value of T_GM_PART_TYPE.PART_TYPE_DIS_NAME
   *
   * @mbggenerated
   */
  public String getPartTypeDisName() {
    return partTypeDisName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_TYPE.PART_TYPE_DIS_NAME
   *
   * @param partTypeDisName the value for T_GM_PART_TYPE.PART_TYPE_DIS_NAME
   *
   * @mbggenerated
   */
  public void setPartTypeDisName(String partTypeDisName) {
    this.partTypeDisName = partTypeDisName;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    PartTypeExt other = (PartTypeExt) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getPartTypeRealName() == null ? other.getPartTypeRealName() == null : this
            .getPartTypeRealName().equals(other.getPartTypeRealName()))
        && (this.getPartTypeDisName() == null ? other.getPartTypeDisName() == null : this
            .getPartTypeDisName().equals(other.getPartTypeDisName()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result =
        prime * result + ((getPartTypeRealName() == null) ? 0 : getPartTypeRealName().hashCode());
    result =
        prime * result + ((getPartTypeDisName() == null) ? 0 : getPartTypeDisName().hashCode());
    return result;
  }
}
