package com.csot.gm.materialManage.dao.original.partType;

import com.csot.gm.materialManage.model.original.partType.PartType;
import com.csot.gm.materialManage.model.original.partType.PartTypeCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PartTypeMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  int countByExample(PartTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  int deleteByExample(PartTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  int insert(PartType record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  int insertSelective(PartType record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  List<PartType> selectByExample(PartTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  PartType selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") PartType record,
      @Param("example") PartTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") PartType record, @Param("example") PartTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(PartType record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_TYPE
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(PartType record);
}