package com.csot.gm.materialManage.dao.extension.enumType;

import java.util.List;

import com.csot.gm.materialManage.model.extension.enumType.EnumTypeExt;
import com.csot.gm.materialManage.model.extension.enumType.EnumTypeExtCriteria;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;

public interface EnumTypeExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int countByExample(EnumTypeExtCriteria example);
  
  List<EnumTypeExt> selectAllEnumType();
  
  List<EnumTypeExt> selectByDesc(String enumName);
  
  List<EnumTypeExt> selectByDescLike(String enumTypeName);
}