package com.csot.gm.materialManage.dao.original.flowNo;

import com.csot.gm.materialManage.model.original.flowNo.FlowNo;
import com.csot.gm.materialManage.model.original.flowNo.FlowNoCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface FlowNoMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int countByExample(FlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int deleteByExample(FlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String partNum);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int insert(FlowNo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int insertSelective(FlowNo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  List<FlowNo> selectByExample(FlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  FlowNo selectByPrimaryKey(String partNum);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") FlowNo record,
      @Param("example") FlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") FlowNo record, @Param("example") FlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(FlowNo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_FLOW_NO
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(FlowNo record);
}