package com.csot.gm.materialManage.dao.extension.gmPartNoPrecode;

import java.util.List;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;

import com.csot.gm.materialManage.model.extension.gmPartNoPrecode.GmPartNoPrecodeExt;
import com.csot.gm.materialManage.model.extension.gmPartNoPrecode.GmPartNoPrecodeExtCriteria;

public interface GmPartNoPrecodeExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int countByExample(GmPartNoPrecodeExtCriteria example);
  
  List<GmPartNoPrecodeExt> selectByKeyCode(String keyCode);
}