/**
 * Please modify this class to meet your needs This class is not complete
 */

package com.csot.gm.esbws.account;

import java.util.List;
import java.util.logging.Logger;

import javax.annotation.Resource;

import com.csot.gm.esbws.account.ESBESBESBImportUserAccountInfoRouteSrvInputCollection;
import com.csot.gm.esbws.account.ESBESBESBImportUserAccountInfoRouteSrvInputItem;
import com.csot.gm.esbws.account.ESBESBESBImportUserAccountInfoRouteSrvResponse;
import com.csot.gm.esbws.account.ErrorCollection;
import com.csot.gm.esbws.account.ErrorItem;
import com.csot.gm.esbws.account.ResponseCollection;
import com.csot.gm.esbws.account.ResponseItem;
import com.csot.gm.esbws.service.AccountInfoService;

/**
 * This class was generated by Apache CXF 2.5.2 2016-08-19T09:22:03.347+08:00 Generated source
 * version: 2.5.2
 * 
 */

@javax.jws.WebService(
    serviceName = "ESB_ESB_ESB_ImportUserAccountInfoRouteSrv.serviceagent",
    portName = "ESB_ESB_ESB_ImportUserAccountInfoRouteSrv",
    targetNamespace = "http://www.csot.tcl.com/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/1.0",
    wsdlLocation = "file:/D:/Study/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv.wsdl",
    endpointInterface = "com.csot.gm.esbws.account.ESBESBESBImportUserAccountInfoRouteSrv")
public class ESBESBESBImportUserAccountInfoRouteSrvImpl implements
    ESBESBESBImportUserAccountInfoRouteSrv {

  private static final Logger LOG = Logger
      .getLogger(ESBESBESBImportUserAccountInfoRouteSrvImpl.class.getName());

  @Resource(name = "accountInfoService")
  private AccountInfoService accountInfoService;

  /*
   * (non-Javadoc)
   * 
   * @see com.csot.gm.esbws.account.ESBESBESBImportUserAccountInfoRouteSrv#process(com.csot.gm.esbws
   * .account.ESBESBESBImportUserAccountInfoRouteSrvRequest payload )*
   */
  @Override
  public com.csot.gm.esbws.account.ESBESBESBImportUserAccountInfoRouteSrvResponse process(
      ESBESBESBImportUserAccountInfoRouteSrvRequest payload) {

    // 记录本次调用的ID，便于发生错误时检查
    String processId = Integer.toString(payload.hashCode());
    LOG.info("Executing operation process. ID: " + processId);
    try {
      ESBESBESBImportUserAccountInfoRouteSrvResponse _return =
          new ESBESBESBImportUserAccountInfoRouteSrvResponse();
      ResponseCollection responseCollection = new ResponseCollection();
      ErrorCollection errorCollection = new ErrorCollection();
      List<ResponseItem> responseItemList = responseCollection.getResponseItem();
      List<ErrorItem> errorItemList = errorCollection.getErrorItem();

      ESBESBESBImportUserAccountInfoRouteSrvInputCollection inputCollection =
          payload.getESBESBESBImportUserAccountInfoRouteSrvInputCollection();
      List<ESBESBESBImportUserAccountInfoRouteSrvInputItem> inputItemList =
          inputCollection.getESBESBESBImportUserAccountInfoRouteSrvInputItem();

      // 循环将账号信息写入T_GM_USER_INFO表
      for (ESBESBESBImportUserAccountInfoRouteSrvInputItem inputItem : inputItemList) {
        try {
          LOG.info("begin-----");
          LOG.info(inputItem.getCNAME());
          accountInfoService.updateAccountInfo(inputItem, processId, responseItemList,
              errorItemList);
        } catch (java.lang.Exception ex) {
          LOG.info("exceptionMsg: " + ex.getMessage());
          throw new RuntimeException(ex);
        }
      }
      String serviceFlag = "TRUE";
      StringBuilder serviceMsg =
          new StringBuilder(100).append("接收").append(inputItemList.size()).append("记录,共导入")
              .append(responseItemList.size() + errorItemList.size()).append("条记录，成功")
              .append(responseItemList.size()).append("条");
      if (!errorItemList.isEmpty()) {
        serviceFlag = "FALSE";
        serviceMsg.append(",失败").append(errorItemList.size()).append("条");
      }
      _return.setResponseCollection(responseCollection);
      _return.setErrorCollection(errorCollection);
      _return.setSERVICEFLAG(serviceFlag);
      _return.setSERVICEMESSAGE(serviceMsg.toString());

      LOG.info("Complete operation process. ID: " + processId);
      return _return;
    } catch (java.lang.Exception ex) {
      throw new RuntimeException(ex);
    }
  }

}
