package com.csot.gm.materialManage.dao.original.gmMissingFlowNo;

import com.csot.gm.materialManage.model.original.gmMissingFlowNo.GmMissingFlowNo;
import com.csot.gm.materialManage.model.original.gmMissingFlowNo.GmMissingFlowNoCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface GmMissingFlowNoMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  int countByExample(GmMissingFlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  int deleteByExample(GmMissingFlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  int insert(GmMissingFlowNo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  int insertSelective(GmMissingFlowNo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  List<GmMissingFlowNo> selectByExample(GmMissingFlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  GmMissingFlowNo selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") GmMissingFlowNo record,
      @Param("example") GmMissingFlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") GmMissingFlowNo record,
      @Param("example") GmMissingFlowNoCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(GmMissingFlowNo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_MISSING_FLOW_NO
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(GmMissingFlowNo record);
}