package com.csot.gm.materialManage.dao.original.gmPartNoPrecode;

import com.csot.gm.materialManage.model.original.gmPartNoPrecode.GmPartNoPrecode;
import com.csot.gm.materialManage.model.original.gmPartNoPrecode.GmPartNoPrecodeCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface GmPartNoPrecodeMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int countByExample(GmPartNoPrecodeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int deleteByExample(GmPartNoPrecodeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int insert(GmPartNoPrecode record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int insertSelective(GmPartNoPrecode record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  List<GmPartNoPrecode> selectByExample(GmPartNoPrecodeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  GmPartNoPrecode selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") GmPartNoPrecode record,
      @Param("example") GmPartNoPrecodeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") GmPartNoPrecode record,
      @Param("example") GmPartNoPrecodeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(GmPartNoPrecode record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_PRECODE
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(GmPartNoPrecode record);
}