package com.csot.gm.materialManage.dao.extension.propertyRtn;

import java.util.List;

import com.csot.gm.materialManage.model.extension.propertyRtn.PropertyRtnExt;
import com.csot.gm.materialManage.model.extension.propertyRtn.PropertyRtnExtCriteria;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;

public interface PropertyRtnExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int countByExample(PropertyRtnExtCriteria example);
  
  List<PropertyRtnExt> selectByUid(String uid);
  
  int deleteAll();
}