/**
 * Please modify this class to meet your needs This class is not complete
 */

package com.csot.gm.esbws.org;

import java.util.List;
import java.util.logging.Logger;

import javax.annotation.Resource;

import com.csot.gm.esbws.service.OrgInfoService;

/**
 * This class was generated by Apache CXF 2.5.2 2016-08-19T09:33:08.093+08:00 Generated source
 * version: 2.5.2
 * 
 */

@javax.jws.WebService(
    serviceName = "ESB_ESB_ESB_ImportOrgInfoRouteSrv.serviceagent",
    portName = "ESB_ESB_ESB_ImportOrgInfoRouteSrv",
    targetNamespace = "http://www.csot.tcl.com/ESB_ESB_ESB_ImportOrgInfoRouteSrv/1.0",
    wsdlLocation = "file:/D:/Study/ESB_ESB_ESB_ImportOrgInfoRouteSrv/ESB_ESB_ESB_ImportOrgInfoRouteSrv.wsdl",
    endpointInterface = "com.csot.gm.esbws.org.ESBESBESBImportOrgInfoRouteSrv")
public class ESBESBESBImportOrgInfoRouteSrvImpl implements ESBESBESBImportOrgInfoRouteSrv {

  private static final Logger LOG = Logger.getLogger(ESBESBESBImportOrgInfoRouteSrvImpl.class
      .getName());

  @Resource(name = "orgInfoService")
  private OrgInfoService orgInfoService;

  /*
   * (non-Javadoc)
   * 
   * @see com.csot.gm.esbws.org.ESBESBESBImportOrgInfoRouteSrv#process(com.csot.gm.esbws.
   * org.ESBESBESBImportOrgInfoRouteSrvRequest payload )*
   */
  @Override
  public com.csot.gm.esbws.org.ESBESBESBImportOrgInfoRouteSrvResponse process(
      ESBESBESBImportOrgInfoRouteSrvRequest payload) {
    // 记录本次调用的ID，便于发生错误时检查
    String processId = Integer.toString(payload.hashCode());
    LOG.info("Executing operation process. ID: " + processId);
    try {
      ESBESBESBImportOrgInfoRouteSrvResponse _return = new ESBESBESBImportOrgInfoRouteSrvResponse();
      ResponseCollection responseCollection = new ResponseCollection();
      ErrorCollection errorCollection = new ErrorCollection();
      List<ResponseItem> responseItemList = responseCollection.getResponseItem();
      List<ErrorItem> errorItemList = errorCollection.getErrorItem();

      ESBESBESBImportOrgInfoRouteSrvInputCollection inputCollection =
          payload.getESBESBESBImportOrgInfoRouteSrvInputCollection();
      List<ESBESBESBImportOrgInfoRouteSrvInputItem> inputItemList =
          inputCollection.getESBESBESBImportOrgInfoRouteSrvInputItem();

      // 循环将账号信息写入T_GM_USER_INFO表
      for (ESBESBESBImportOrgInfoRouteSrvInputItem inputItem : inputItemList) {
        try {
          LOG.info("begin-----");
          LOG.info(inputItem.getCORGNAME());
          orgInfoService.updateOrgInfo(inputItem, processId, responseItemList, errorItemList);
        } catch (java.lang.Exception ex) {
          LOG.info("exceptionMsg: " + ex.getMessage());
          throw new RuntimeException(ex);
        }
      }
      String serviceFlag = "TRUE";
      StringBuilder serviceMsg =
          new StringBuilder(100).append("接收").append(inputItemList.size()).append("记录,共导入")
              .append(responseItemList.size() + errorItemList.size()).append("条记录，成功")
              .append(responseItemList.size()).append("条");
      if (!errorItemList.isEmpty()) {
        serviceFlag = "FALSE";
        serviceMsg.append(",失败").append(errorItemList.size()).append("条");
      }
      _return.setResponseCollection(responseCollection);
      _return.setErrorCollection(errorCollection);
      _return.setSERVICEFLAG(serviceFlag);
      _return.setSERVICEMESSAGE(serviceMsg.toString());

      LOG.info("Complete operation process. ID: " + processId);
      return _return;
    } catch (java.lang.Exception ex) {
      LOG.info("exceptionMsg: " + ex.getMessage());
      throw new RuntimeException(ex);
    }
  }

}
