package com.csot.gm.materialManage.dao.extension.part;

import java.util.List;

import com.csot.gm.materialManage.model.extension.part.PartExtCriteria;
import com.csot.gm.materialManage.model.original.part.Part;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PartExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  int countByExample(PartExtCriteria example);
  
  List<Part> getAllPart();
  
  List<Part> getByPartName(String partName);
  
  List<Part> getByPartNameAndParentId(@Param("partName") String partName,
      @Param("parentId") String parentId);
  
  List<Part> getByParentId(String parentId);
}