package com.csot.gm.esbws.org;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2 2016-08-19T09:33:08.173+08:00 Generated source
 * version: 2.5.2
 * 
 */
@WebServiceClient(
    name = "ESB_ESB_ESB_ImportOrgInfoRouteSrv.serviceagent",
    wsdlLocation = "file:/D:/Study/ESB_ESB_ESB_ImportOrgInfoRouteSrv/ESB_ESB_ESB_ImportOrgInfoRouteSrv.wsdl",
    targetNamespace = "http://www.csot.tcl.com/ESB_ESB_ESB_ImportOrgInfoRouteSrv/1.0")
public class ESBESBESBImportOrgInfoRouteSrvServiceagent extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName(
      "http://www.csot.tcl.com/ESB_ESB_ESB_ImportOrgInfoRouteSrv/1.0",
      "ESB_ESB_ESB_ImportOrgInfoRouteSrv.serviceagent");
  public final static QName ESBESBESBImportOrgInfoRouteSrv = new QName(
      "http://www.csot.tcl.com/ESB_ESB_ESB_ImportOrgInfoRouteSrv/1.0",
      "ESB_ESB_ESB_ImportOrgInfoRouteSrv");

  static {
    URL url = null;
    try {
      url =
          new URL(
              "file:/D:/Study/ESB_ESB_ESB_ImportOrgInfoRouteSrv/ESB_ESB_ESB_ImportOrgInfoRouteSrv.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger
          .getLogger(ESBESBESBImportOrgInfoRouteSrvServiceagent.class.getName())
          .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
              "file:/D:/Study/ESB_ESB_ESB_ImportOrgInfoRouteSrv/ESB_ESB_ESB_ImportOrgInfoRouteSrv.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public ESBESBESBImportOrgInfoRouteSrvServiceagent(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public ESBESBESBImportOrgInfoRouteSrvServiceagent(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public ESBESBESBImportOrgInfoRouteSrvServiceagent() {
    super(WSDL_LOCATION, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBESBESBImportOrgInfoRouteSrvServiceagent(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBESBESBImportOrgInfoRouteSrvServiceagent(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBESBESBImportOrgInfoRouteSrvServiceagent(URL wsdlLocation, QName serviceName,
      WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns ESBESBESBImportOrgInfoRouteSrv
   */
  @WebEndpoint(name = "ESB_ESB_ESB_ImportOrgInfoRouteSrv")
  public ESBESBESBImportOrgInfoRouteSrv getESBESBESBImportOrgInfoRouteSrv() {
    return super.getPort(ESBESBESBImportOrgInfoRouteSrv, ESBESBESBImportOrgInfoRouteSrv.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns ESBESBESBImportOrgInfoRouteSrv
   */
  @WebEndpoint(name = "ESB_ESB_ESB_ImportOrgInfoRouteSrv")
  public ESBESBESBImportOrgInfoRouteSrv getESBESBESBImportOrgInfoRouteSrv(
      WebServiceFeature... features) {
    return super.getPort(ESBESBESBImportOrgInfoRouteSrv, ESBESBESBImportOrgInfoRouteSrv.class,
        features);
  }

}
