package com.csot.gm.materialManage.dao.extension.properties;

import java.util.List;

import com.csot.gm.materialManage.model.extension.properties.PartPropertiesExt;
import com.csot.gm.materialManage.model.extension.properties.PartPropertiesExtCriteria;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PartPropertiesExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTIES
   *
   * @mbggenerated
   */
  int countByExample(PartPropertiesExtCriteria example);
  
  List<PartPropertiesExt> getPropertiesByPartId(String partId);
  
  List<PartPropertiesExt> getEnumPropertiesByPartId(@Param("partId") String partId,
      @Param("isEnum") String isEnum);
  
  List<PartPropertiesExt> getPropertyByPartIdAndProName(@Param("partId") String partId,
      @Param("proName") String proName);
  
  List<PartPropertiesExt> getPropertiesByPartIdAndUnique(@Param("partId") String partId,
      @Param("isUnique") String isUnique);
  
  List<PartPropertiesExt> getIdByPartIdAndProDisName(@Param("partId") String partId,
      @Param("propertyDisName") String propertyDisName);
}