package com.csot.gm.materialManage.model.original.file;

import java.io.Serializable;
import java.util.Date;

public class FileUpload implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.ID
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.FILE_TYPE
   *
   * @mbggenerated
   */
  private String fileType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.FILE_NAME
   *
   * @mbggenerated
   */
  private String fileName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.CREATE_NAME
   *
   * @mbggenerated
   */
  private String createName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.APPLICANT_CODE
   *
   * @mbggenerated
   */
  private String applicantCode;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.APPLICANT_NAME
   *
   * @mbggenerated
   */
  private String applicantName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.CREATE_TIME
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.FILE_LOCATION
   *
   * @mbggenerated
   */
  private String fileLocation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.FILE_SIZE
   *
   * @mbggenerated
   */
  private String fileSize;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_FILE_UPLOAD.REMARK
   *
   * @mbggenerated
   */
  private String remark;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_FILE_UPLOAD
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.ID
   *
   * @return the value of T_GM_FILE_UPLOAD.ID
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.ID
   *
   * @param id the value for T_GM_FILE_UPLOAD.ID
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.FILE_TYPE
   *
   * @return the value of T_GM_FILE_UPLOAD.FILE_TYPE
   *
   * @mbggenerated
   */
  public String getFileType() {
    return fileType;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.FILE_TYPE
   *
   * @param fileType the value for T_GM_FILE_UPLOAD.FILE_TYPE
   *
   * @mbggenerated
   */
  public void setFileType(String fileType) {
    this.fileType = fileType;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.FILE_NAME
   *
   * @return the value of T_GM_FILE_UPLOAD.FILE_NAME
   *
   * @mbggenerated
   */
  public String getFileName() {
    return fileName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.FILE_NAME
   *
   * @param fileName the value for T_GM_FILE_UPLOAD.FILE_NAME
   *
   * @mbggenerated
   */
  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.CREATE_NAME
   *
   * @return the value of T_GM_FILE_UPLOAD.CREATE_NAME
   *
   * @mbggenerated
   */
  public String getCreateName() {
    return createName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.CREATE_NAME
   *
   * @param createName the value for T_GM_FILE_UPLOAD.CREATE_NAME
   *
   * @mbggenerated
   */
  public void setCreateName(String createName) {
    this.createName = createName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.APPLICANT_CODE
   *
   * @return the value of T_GM_FILE_UPLOAD.APPLICANT_CODE
   *
   * @mbggenerated
   */
  public String getApplicantCode() {
    return applicantCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.APPLICANT_CODE
   *
   * @param applicantCode the value for T_GM_FILE_UPLOAD.APPLICANT_CODE
   *
   * @mbggenerated
   */
  public void setApplicantCode(String applicantCode) {
    this.applicantCode = applicantCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.APPLICANT_NAME
   *
   * @return the value of T_GM_FILE_UPLOAD.APPLICANT_NAME
   *
   * @mbggenerated
   */
  public String getApplicantName() {
    return applicantName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.APPLICANT_NAME
   *
   * @param applicantName the value for T_GM_FILE_UPLOAD.APPLICANT_NAME
   *
   * @mbggenerated
   */
  public void setApplicantName(String applicantName) {
    this.applicantName = applicantName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.CREATE_TIME
   *
   * @return the value of T_GM_FILE_UPLOAD.CREATE_TIME
   *
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.CREATE_TIME
   *
   * @param createTime the value for T_GM_FILE_UPLOAD.CREATE_TIME
   *
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.FILE_LOCATION
   *
   * @return the value of T_GM_FILE_UPLOAD.FILE_LOCATION
   *
   * @mbggenerated
   */
  public String getFileLocation() {
    return fileLocation;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.FILE_LOCATION
   *
   * @param fileLocation the value for T_GM_FILE_UPLOAD.FILE_LOCATION
   *
   * @mbggenerated
   */
  public void setFileLocation(String fileLocation) {
    this.fileLocation = fileLocation;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.FILE_SIZE
   *
   * @return the value of T_GM_FILE_UPLOAD.FILE_SIZE
   *
   * @mbggenerated
   */
  public String getFileSize() {
    return fileSize;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.FILE_SIZE
   *
   * @param fileSize the value for T_GM_FILE_UPLOAD.FILE_SIZE
   *
   * @mbggenerated
   */
  public void setFileSize(String fileSize) {
    this.fileSize = fileSize;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_FILE_UPLOAD.REMARK
   *
   * @return the value of T_GM_FILE_UPLOAD.REMARK
   *
   * @mbggenerated
   */
  public String getRemark() {
    return remark;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_FILE_UPLOAD.REMARK
   *
   * @param remark the value for T_GM_FILE_UPLOAD.REMARK
   *
   * @mbggenerated
   */
  public void setRemark(String remark) {
    this.remark = remark;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_FILE_UPLOAD
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    FileUpload other = (FileUpload) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getFileType() == null ? other.getFileType() == null : this.getFileType().equals(
            other.getFileType()))
        && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(
            other.getFileName()))
        && (this.getCreateName() == null ? other.getCreateName() == null : this.getCreateName()
            .equals(other.getCreateName()))
        && (this.getApplicantCode() == null ? other.getApplicantCode() == null : this
            .getApplicantCode().equals(other.getApplicantCode()))
        && (this.getApplicantName() == null ? other.getApplicantName() == null : this
            .getApplicantName().equals(other.getApplicantName()))
        && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime()
            .equals(other.getCreateTime()))
        && (this.getFileLocation() == null ? other.getFileLocation() == null : this
            .getFileLocation().equals(other.getFileLocation()))
        && (this.getFileSize() == null ? other.getFileSize() == null : this.getFileSize().equals(
            other.getFileSize()))
        && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(
            other.getRemark()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_FILE_UPLOAD
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result = prime * result + ((getFileType() == null) ? 0 : getFileType().hashCode());
    result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
    result = prime * result + ((getCreateName() == null) ? 0 : getCreateName().hashCode());
    result = prime * result + ((getApplicantCode() == null) ? 0 : getApplicantCode().hashCode());
    result = prime * result + ((getApplicantName() == null) ? 0 : getApplicantName().hashCode());
    result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
    result = prime * result + ((getFileLocation() == null) ? 0 : getFileLocation().hashCode());
    result = prime * result + ((getFileSize() == null) ? 0 : getFileSize().hashCode());
    result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
    return result;
  }
}
