package com.csot.gm.materialManage.dao.extension.typePartM;

import java.util.List;

import com.csot.gm.materialManage.model.extension.typePartM.TypePartMExt;
import com.csot.gm.materialManage.model.extension.typePartM.TypePartMExtCriteria;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;

public interface TypePartMExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  int countByExample(TypePartMExtCriteria example);
  
  List<TypePartMExt> getByPartTypeId(String partTypeId);
  
  void deleteByPartId(String partId);
  
  List<TypePartMExt> getByPartId(String partId);
}