package com.csot.gm.materialManage.dao.original.gmPartDescRuleMap;

import com.csot.gm.materialManage.model.original.gmPartDescRuleMap.GmPartDescRuleMap;
import com.csot.gm.materialManage.model.original.gmPartDescRuleMap.GmPartDescRuleMapCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface GmPartDescRuleMapMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int countByExample(GmPartDescRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int deleteByExample(GmPartDescRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int insert(GmPartDescRuleMap record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int insertSelective(GmPartDescRuleMap record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  List<GmPartDescRuleMap> selectByExample(GmPartDescRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  GmPartDescRuleMap selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") GmPartDescRuleMap record,
      @Param("example") GmPartDescRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") GmPartDescRuleMap record,
      @Param("example") GmPartDescRuleMapCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(GmPartDescRuleMap record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(GmPartDescRuleMap record);
}