package com.csot.gm.materialManage.model.extension.gmlog;

import java.io.Serializable;
import java.util.Date;

public class LogExt implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_LOG.ID
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_LOG.USER_NAME
   *
   * @mbggenerated
   */
  private String userName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_LOG.CREATE_TIME
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_LOG.CONTENT
   *
   * @mbggenerated
   */
  private String content;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_LOG.OPERATION
   *
   * @mbggenerated
   */
  private String operation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_LOG
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_LOG.ID
   *
   * @return the value of T_GM_LOG.ID
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_LOG.ID
   *
   * @param id the value for T_GM_LOG.ID
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_LOG.USER_NAME
   *
   * @return the value of T_GM_LOG.USER_NAME
   *
   * @mbggenerated
   */
  public String getUserName() {
    return userName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_LOG.USER_NAME
   *
   * @param userName the value for T_GM_LOG.USER_NAME
   *
   * @mbggenerated
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_LOG.CREATE_TIME
   *
   * @return the value of T_GM_LOG.CREATE_TIME
   *
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_LOG.CREATE_TIME
   *
   * @param createTime the value for T_GM_LOG.CREATE_TIME
   *
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_LOG.CONTENT
   *
   * @return the value of T_GM_LOG.CONTENT
   *
   * @mbggenerated
   */
  public String getContent() {
    return content;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_LOG.CONTENT
   *
   * @param content the value for T_GM_LOG.CONTENT
   *
   * @mbggenerated
   */
  public void setContent(String content) {
    this.content = content;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_LOG.OPERATION
   *
   * @return the value of T_GM_LOG.OPERATION
   *
   * @mbggenerated
   */
  public String getOperation() {
    return operation;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_LOG.OPERATION
   *
   * @param operation the value for T_GM_LOG.OPERATION
   *
   * @mbggenerated
   */
  public void setOperation(String operation) {
    this.operation = operation;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_LOG
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    LogExt other = (LogExt) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(
            other.getUserName()))
        && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime()
            .equals(other.getCreateTime()))
        && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(
            other.getContent()))
        && (this.getOperation() == null ? other.getOperation() == null : this.getOperation()
            .equals(other.getOperation()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_LOG
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
    result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
    result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
    result = prime * result + ((getOperation() == null) ? 0 : getOperation().hashCode());
    return result;
  }
}
