package com.csot.gm.materialManage.dao.original.propertyRtn;

import com.csot.gm.materialManage.model.original.propertyRtn.PropertyRtn;
import com.csot.gm.materialManage.model.original.propertyRtn.PropertyRtnCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PropertyRtnMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int countByExample(PropertyRtnCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int deleteByExample(PropertyRtnCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int insert(PropertyRtn record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int insertSelective(PropertyRtn record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  List<PropertyRtn> selectByExample(PropertyRtnCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  PropertyRtn selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") PropertyRtn record,
      @Param("example") PropertyRtnCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") PropertyRtn record,
      @Param("example") PropertyRtnCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(PropertyRtn record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_RTN
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(PropertyRtn record);
}
