package com.csot.gm.materialManage.dao.extension.gmlog;

import com.csot.gm.materialManage.model.extension.gmlog.LogExtCriteria;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;

public interface LogExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_LOG
   *
   * @mbggenerated
   */
  int countByExample(LogExtCriteria example);
}