package com.csot.gm.materialManage.dao.extension.wxmap;

import java.util.List;

import com.csot.gm.materialManage.model.extension.wxmap.WXMapExt;
import com.csot.gm.materialManage.model.extension.wxmap.WXMapExtCriteria;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;

public interface WXMapExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int countByExample(WXMapExtCriteria example);
  
  List<WXMapExt> selectByWXCode(String wxCode);
  
  List<WXMapExt> selectBySpareCode(String spareCode);
}