package com.csot.gm.materialManage.dao.original.propertiesM;

import com.csot.gm.materialManage.model.original.propertiesM.PropertiesM;
import com.csot.gm.materialManage.model.original.propertiesM.PropertiesMCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PropertiesMMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int countByExample(PropertiesMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int deleteByExample(PropertiesMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int insert(PropertiesM record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int insertSelective(PropertiesM record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  List<PropertiesM> selectByExample(PropertiesMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  PropertiesM selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") PropertiesM record,
      @Param("example") PropertiesMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") PropertiesM record,
      @Param("example") PropertiesMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(PropertiesM record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(PropertiesM record);
}
