package com.csot.gm.materialManage.dao.extension.systemNotice;

import com.csot.gm.materialManage.model.extension.systemNotice.SystemNoticeExtCriteria;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;

public interface SystemNoticeExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int countByExample(SystemNoticeExtCriteria example);
}