package com.csot.gm.materialManage.dao.extension.propertiesM;

import java.util.List;

import com.csot.gm.materialManage.model.extension.propertiesM.PropertiesMExt;
import com.csot.gm.materialManage.model.extension.propertiesM.PropertiesMExtCriteria;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PropertiesMExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  int countByExample(PropertiesMExtCriteria example);
  
  List<PropertiesMExt> getEnumIdByPropertyId(String propertyId);
  
  List<PropertiesMExt> getPropertyIdByEnumId(String enumId);
  
  int updateEnumTypeByPropertyId(@Param("propertyId") String propertyId,
      @Param("enumTypeId") String enumTypeId);
  
}