package com.csot.gm.materialManage.dao.extension.clean;

import java.util.List;

import com.csot.gm.materialManage.model.extension.clean.CleanExt;
import com.csot.gm.materialManage.model.extension.clean.CleanExtCriteria;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface CleanExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_CLEAN
   *
   * @mbggenerated
   */
  int countByExample(CleanExtCriteria example);

  List<CleanExt> selectBySpec(String spec);

  List<CleanExt> selectByBrandSpec(@Param("spec") String spec, @Param("brand") String brand);
  
  List<CleanExt> selectByPartNo(String partNo);
}
