package com.csot.gm.materialManage.dao.original.clean;

import com.csot.gm.materialManage.model.original.clean.Clean;
import com.csot.gm.materialManage.model.original.clean.CleanCriteria;
import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface CleanMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  int countByExample(CleanCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  int deleteByExample(CleanCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  int insert(Clean record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  int insertSelective(Clean record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  List<Clean> selectByExample(CleanCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  Clean selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") Clean record, @Param("example") CleanCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") Clean record, @Param("example") CleanCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(Clean record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLEAN
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Clean record);
}