package com.csot.gm.materialManage.dao.extension.gmPartDescRuleMap;

import java.util.List;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;

import com.csot.gm.materialManage.model.extension.gmPartDescRuleMap.GmPartDescRuleMapExt;
import com.csot.gm.materialManage.model.extension.gmPartDescRuleMap.GmPartDescRuleMapExtCriteria;

public interface GmPartDescRuleMapExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  int countByExample(GmPartDescRuleMapExtCriteria example);
  
  List<GmPartDescRuleMapExt> selectByKeyCode(String keyCode);
}