package com.csot.gm.esbws.account;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-08-19T09:22:03.443+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.csot.tcl.com/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/1.0", name = "ESB_ESB_ESB_ImportUserAccountInfoRouteSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ESBESBESBImportUserAccountInfoRouteSrv {

    @WebResult(name = "ESB_ESB_ESB_ImportUserAccountInfoRouteSrvResponse", targetNamespace = "http://www.csot.tcl.com/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/1.0", partName = "payload")
    @WebMethod(action = "/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/v1/process")
    public ESBESBESBImportUserAccountInfoRouteSrvResponse process(
        @WebParam(partName = "payload", name = "ESB_ESB_ESB_ImportUserAccountInfoRouteSrvRequest", targetNamespace = "http://www.csot.tcl.com/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/1.0")
        ESBESBESBImportUserAccountInfoRouteSrvRequest payload
    );
}
