package com.csot.gm.materialManage.dao.original.typePartM;

import com.csot.gm.materialManage.model.original.typePartM.TypePartM;
import com.csot.gm.materialManage.model.original.typePartM.TypePartMCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface TypePartMMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  int countByExample(TypePartMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  int deleteByExample(TypePartMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  int insert(TypePartM record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  int insertSelective(TypePartM record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  List<TypePartM> selectByExample(TypePartMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  TypePartM selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") TypePartM record,
      @Param("example") TypePartMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
      int
      updateByExample(@Param("record") TypePartM record, @Param("example") TypePartMCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(TypePartM record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(TypePartM record);
}
