package com.csot.gm.materialManage.dao.extension.valueEnumM;

import java.util.List;

import com.csot.gm.materialManage.model.extension.valueEnumM.ValueEnumMExtCriteria;
import com.csot.gm.materialManage.model.original.valueEnumM.ValueEnumM;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface ValueEnumMExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_VALUE_ENUM_MAPPING
   *
   * @mbggenerated
   */
  int countByExample(ValueEnumMExtCriteria example);
  
  List<ValueEnumM> getByValueId(String valueId);
  
  int updateValueEnumMByValueId(@Param("valueId") String valueId,
      @Param("enumTypeId") String enumTypeId);
}