package com.csot.gm.esbws.account;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2 2016-08-19T09:22:03.589+08:00 Generated source
 * version: 2.5.2
 * 
 */
@WebServiceClient(
    name = "ESB_ESB_ESB_ImportUserAccountInfoRouteSrv.serviceagent",
    wsdlLocation = "file:/D:/Study/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv.wsdl",
    targetNamespace = "http://www.csot.tcl.com/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/1.0")
public class ESBESBESBImportUserAccountInfoRouteSrvServiceagent extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName(
      "http://www.csot.tcl.com/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/1.0",
      "ESB_ESB_ESB_ImportUserAccountInfoRouteSrv.serviceagent");
  public final static QName ESBESBESBImportUserAccountInfoRouteSrv = new QName(
      "http://www.csot.tcl.com/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/1.0",
      "ESB_ESB_ESB_ImportUserAccountInfoRouteSrv");

  static {
    URL url = null;
    try {
      url =
          new URL(
              "file:/D:/Study/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger
          .getLogger(ESBESBESBImportUserAccountInfoRouteSrvServiceagent.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:/D:/Study/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv/ESB_ESB_ESB_ImportUserAccountInfoRouteSrv.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public ESBESBESBImportUserAccountInfoRouteSrvServiceagent(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public ESBESBESBImportUserAccountInfoRouteSrvServiceagent(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public ESBESBESBImportUserAccountInfoRouteSrvServiceagent() {
    super(WSDL_LOCATION, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBESBESBImportUserAccountInfoRouteSrvServiceagent(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBESBESBImportUserAccountInfoRouteSrvServiceagent(URL wsdlLocation,
      WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBESBESBImportUserAccountInfoRouteSrvServiceagent(URL wsdlLocation, QName serviceName,
      WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns ESBESBESBImportUserAccountInfoRouteSrv
   */
  @WebEndpoint(name = "ESB_ESB_ESB_ImportUserAccountInfoRouteSrv")
  public ESBESBESBImportUserAccountInfoRouteSrv getESBESBESBImportUserAccountInfoRouteSrv() {
    return super.getPort(ESBESBESBImportUserAccountInfoRouteSrv,
        ESBESBESBImportUserAccountInfoRouteSrv.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns ESBESBESBImportUserAccountInfoRouteSrv
   */
  @WebEndpoint(name = "ESB_ESB_ESB_ImportUserAccountInfoRouteSrv")
  public ESBESBESBImportUserAccountInfoRouteSrv getESBESBESBImportUserAccountInfoRouteSrv(
      WebServiceFeature... features) {
    return super.getPort(ESBESBESBImportUserAccountInfoRouteSrv,
        ESBESBESBImportUserAccountInfoRouteSrv.class, features);
  }

}
