package com.csot.gm.materialManage.dao.original.partClass;

import com.csot.gm.materialManage.model.original.partClass.PartClass;
import com.csot.gm.materialManage.model.original.partClass.PartClassCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PartClassMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  int countByExample(PartClassCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  int deleteByExample(PartClassCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  int insert(PartClass record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  int insertSelective(PartClass record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  List<PartClass> selectByExample(PartClassCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  PartClass selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") PartClass record,
      @Param("example") PartClassCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
      int
      updateByExample(@Param("record") PartClass record, @Param("example") PartClassCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(PartClass record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(PartClass record);
}