package com.csot.gm.materialManage.model.extension.systemNotice;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.amberframework.core.mybatis.pojo.Page;

public class SystemNoticeExtCriteria {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  protected Page page;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public SystemNoticeExtCriteria() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public void setPage(Page page) {
    this.page = page;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public Page getPage() {
    return this.page;
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("ID is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("ID is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(String value) {
      addCriterion("ID =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(String value) {
      addCriterion("ID <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(String value) {
      addCriterion("ID >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(String value) {
      addCriterion("ID >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(String value) {
      addCriterion("ID <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(String value) {
      addCriterion("ID <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLike(String value) {
      addCriterion("ID like", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotLike(String value) {
      addCriterion("ID not like", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<String> values) {
      addCriterion("ID in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<String> values) {
      addCriterion("ID not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(String value1, String value2) {
      addCriterion("ID between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(String value1, String value2) {
      addCriterion("ID not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleIsNull() {
      addCriterion("NOTICE_TITLE is null");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleIsNotNull() {
      addCriterion("NOTICE_TITLE is not null");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleEqualTo(String value) {
      addCriterion("NOTICE_TITLE =", value, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleNotEqualTo(String value) {
      addCriterion("NOTICE_TITLE <>", value, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleGreaterThan(String value) {
      addCriterion("NOTICE_TITLE >", value, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleGreaterThanOrEqualTo(String value) {
      addCriterion("NOTICE_TITLE >=", value, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleLessThan(String value) {
      addCriterion("NOTICE_TITLE <", value, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleLessThanOrEqualTo(String value) {
      addCriterion("NOTICE_TITLE <=", value, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleLike(String value) {
      addCriterion("NOTICE_TITLE like", value, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleNotLike(String value) {
      addCriterion("NOTICE_TITLE not like", value, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleIn(List<String> values) {
      addCriterion("NOTICE_TITLE in", values, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleNotIn(List<String> values) {
      addCriterion("NOTICE_TITLE not in", values, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleBetween(String value1, String value2) {
      addCriterion("NOTICE_TITLE between", value1, value2, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleNotBetween(String value1, String value2) {
      addCriterion("NOTICE_TITLE not between", value1, value2, "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelIsNull() {
      addCriterion("NOTICE_LEVEL is null");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelIsNotNull() {
      addCriterion("NOTICE_LEVEL is not null");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelEqualTo(Short value) {
      addCriterion("NOTICE_LEVEL =", value, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelNotEqualTo(Short value) {
      addCriterion("NOTICE_LEVEL <>", value, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelGreaterThan(Short value) {
      addCriterion("NOTICE_LEVEL >", value, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelGreaterThanOrEqualTo(Short value) {
      addCriterion("NOTICE_LEVEL >=", value, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelLessThan(Short value) {
      addCriterion("NOTICE_LEVEL <", value, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelLessThanOrEqualTo(Short value) {
      addCriterion("NOTICE_LEVEL <=", value, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelIn(List<Short> values) {
      addCriterion("NOTICE_LEVEL in", values, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelNotIn(List<Short> values) {
      addCriterion("NOTICE_LEVEL not in", values, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelBetween(Short value1, Short value2) {
      addCriterion("NOTICE_LEVEL between", value1, value2, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andNoticeLevelNotBetween(Short value1, Short value2) {
      addCriterion("NOTICE_LEVEL not between", value1, value2, "noticeLevel");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNull() {
      addCriterion("UPDATE_TIME is null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNotNull() {
      addCriterion("UPDATE_TIME is not null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeEqualTo(Date value) {
      addCriterion("UPDATE_TIME =", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotEqualTo(Date value) {
      addCriterion("UPDATE_TIME <>", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThan(Date value) {
      addCriterion("UPDATE_TIME >", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("UPDATE_TIME >=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThan(Date value) {
      addCriterion("UPDATE_TIME <", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
      addCriterion("UPDATE_TIME <=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIn(List<Date> values) {
      addCriterion("UPDATE_TIME in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotIn(List<Date> values) {
      addCriterion("UPDATE_TIME not in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeBetween(Date value1, Date value2) {
      addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
      addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andIsActiveIsNull() {
      addCriterion("IS_ACTIVE is null");
      return (Criteria) this;
    }

    public Criteria andIsActiveIsNotNull() {
      addCriterion("IS_ACTIVE is not null");
      return (Criteria) this;
    }

    public Criteria andIsActiveEqualTo(String value) {
      addCriterion("IS_ACTIVE =", value, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveNotEqualTo(String value) {
      addCriterion("IS_ACTIVE <>", value, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveGreaterThan(String value) {
      addCriterion("IS_ACTIVE >", value, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveGreaterThanOrEqualTo(String value) {
      addCriterion("IS_ACTIVE >=", value, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveLessThan(String value) {
      addCriterion("IS_ACTIVE <", value, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveLessThanOrEqualTo(String value) {
      addCriterion("IS_ACTIVE <=", value, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveLike(String value) {
      addCriterion("IS_ACTIVE like", value, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveNotLike(String value) {
      addCriterion("IS_ACTIVE not like", value, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveIn(List<String> values) {
      addCriterion("IS_ACTIVE in", values, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveNotIn(List<String> values) {
      addCriterion("IS_ACTIVE not in", values, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveBetween(String value1, String value2) {
      addCriterion("IS_ACTIVE between", value1, value2, "isActive");
      return (Criteria) this;
    }

    public Criteria andIsActiveNotBetween(String value1, String value2) {
      addCriterion("IS_ACTIVE not between", value1, value2, "isActive");
      return (Criteria) this;
    }

    public Criteria andIdLikeInsensitive(String value) {
      addCriterion("upper(ID) like", value.toUpperCase(), "id");
      return (Criteria) this;
    }

    public Criteria andNoticeTitleLikeInsensitive(String value) {
      addCriterion("upper(NOTICE_TITLE) like", value.toUpperCase(), "noticeTitle");
      return (Criteria) this;
    }

    public Criteria andIsActiveLikeInsensitive(String value) {
      addCriterion("upper(IS_ACTIVE) like", value.toUpperCase(), "isActive");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}