
package com.csot.recruit.common.webservice.outside.cjol_pt_map;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-10-22T16:06:09.544+08:00
 * Generated source version: 2.7.12
 * 
 */
public final class ESBGYDGYDInquiryFunctionMappingSrv_ESBGYDGYDInquiryFunctionMappingSrv_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.plm.csot.kmss.landray.com/", "ESB_GYD_GYD_InquiryFunctionMappingSrv.serviceagent");

    private ESBGYDGYDInquiryFunctionMappingSrv_ESBGYDGYDInquiryFunctionMappingSrv_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ESBGYDGYDInquiryFunctionMappingSrvServiceagent.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ESBGYDGYDInquiryFunctionMappingSrvServiceagent ss = new ESBGYDGYDInquiryFunctionMappingSrvServiceagent(wsdlURL, SERVICE_NAME);
        ESBGYDGYDInquiryFunctionMappingSrv port = ss.getESBGYDGYDInquiryFunctionMappingSrv();  
        
        {
        System.out.println("Invoking process...");
        ESBGYDGYDInquiryFunctionMappingSrvRequest _process_payload = null;
        ESBGYDGYDInquiryFunctionMappingSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
