package com.csot.gm.materialManage.dao.original.enumType;

import com.csot.gm.materialManage.model.original.enumType.EnumType;
import com.csot.gm.materialManage.model.original.enumType.EnumTypeCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface EnumTypeMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int countByExample(EnumTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int deleteByExample(EnumTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int insert(EnumType record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int insertSelective(EnumType record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  List<EnumType> selectByExample(EnumTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  EnumType selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") EnumType record,
      @Param("example") EnumTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") EnumType record, @Param("example") EnumTypeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(EnumType record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_ENUM_TYPE
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(EnumType record);
}