package com.csot.gm.materialManage.dao.original.gmPartDescRule;

import com.csot.gm.materialManage.model.original.gmPartDescRule.GmPartDescRule;
import com.csot.gm.materialManage.model.original.gmPartDescRule.GmPartDescRuleCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface GmPartDescRuleMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  int countByExample(GmPartDescRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  int deleteByExample(GmPartDescRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  int insert(GmPartDescRule record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  int insertSelective(GmPartDescRule record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  List<GmPartDescRule> selectByExample(GmPartDescRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  GmPartDescRule selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") GmPartDescRule record,
      @Param("example") GmPartDescRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") GmPartDescRule record,
      @Param("example") GmPartDescRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(GmPartDescRule record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(GmPartDescRule record);
}