package com.csot.gm.materialManage.model.extension.valueEnumM;

import java.io.Serializable;

public class ValueEnumMExt implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_VALUE_ENUM_MAPPING.ID
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_VALUE_ENUM_MAPPING.ENUM_VALUE_ID
   *
   * @mbggenerated
   */
  private String enumValueId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_VALUE_ENUM_MAPPING.ENUM_TYPE_ID
   *
   * @mbggenerated
   */
  private String enumTypeId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_VALUE_ENUM_MAPPING
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_VALUE_ENUM_MAPPING.ID
   *
   * @return the value of T_GM_VALUE_ENUM_MAPPING.ID
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_VALUE_ENUM_MAPPING.ID
   *
   * @param id the value for T_GM_VALUE_ENUM_MAPPING.ID
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_VALUE_ENUM_MAPPING.ENUM_VALUE_ID
   *
   * @return the value of T_GM_VALUE_ENUM_MAPPING.ENUM_VALUE_ID
   *
   * @mbggenerated
   */
  public String getEnumValueId() {
    return enumValueId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_VALUE_ENUM_MAPPING.ENUM_VALUE_ID
   *
   * @param enumValueId the value for T_GM_VALUE_ENUM_MAPPING.ENUM_VALUE_ID
   *
   * @mbggenerated
   */
  public void setEnumValueId(String enumValueId) {
    this.enumValueId = enumValueId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_VALUE_ENUM_MAPPING.ENUM_TYPE_ID
   *
   * @return the value of T_GM_VALUE_ENUM_MAPPING.ENUM_TYPE_ID
   *
   * @mbggenerated
   */
  public String getEnumTypeId() {
    return enumTypeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_VALUE_ENUM_MAPPING.ENUM_TYPE_ID
   *
   * @param enumTypeId the value for T_GM_VALUE_ENUM_MAPPING.ENUM_TYPE_ID
   *
   * @mbggenerated
   */
  public void setEnumTypeId(String enumTypeId) {
    this.enumTypeId = enumTypeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_VALUE_ENUM_MAPPING
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    ValueEnumMExt other = (ValueEnumMExt) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getEnumValueId() == null ? other.getEnumValueId() == null : this.getEnumValueId()
            .equals(other.getEnumValueId()))
        && (this.getEnumTypeId() == null ? other.getEnumTypeId() == null : this.getEnumTypeId()
            .equals(other.getEnumTypeId()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_VALUE_ENUM_MAPPING
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result = prime * result + ((getEnumValueId() == null) ? 0 : getEnumValueId().hashCode());
    result = prime * result + ((getEnumTypeId() == null) ? 0 : getEnumTypeId().hashCode());
    return result;
  }
}
