package com.csot.gm.materialManage.model.original.propertyValue;

import java.util.ArrayList;
import java.util.List;
import org.amberframework.core.mybatis.pojo.Page;

public class PropertyValueCriteria {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  protected Page page;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public PropertyValueCriteria() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public void setPage(Page page) {
    this.page = page;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public Page getPage() {
    return this.page;
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("ID is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("ID is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(String value) {
      addCriterion("ID =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(String value) {
      addCriterion("ID <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(String value) {
      addCriterion("ID >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(String value) {
      addCriterion("ID >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(String value) {
      addCriterion("ID <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(String value) {
      addCriterion("ID <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLike(String value) {
      addCriterion("ID like", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotLike(String value) {
      addCriterion("ID not like", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<String> values) {
      addCriterion("ID in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<String> values) {
      addCriterion("ID not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(String value1, String value2) {
      addCriterion("ID between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(String value1, String value2) {
      addCriterion("ID not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andPropertyNameIsNull() {
      addCriterion("PROPERTY_NAME is null");
      return (Criteria) this;
    }

    public Criteria andPropertyNameIsNotNull() {
      addCriterion("PROPERTY_NAME is not null");
      return (Criteria) this;
    }

    public Criteria andPropertyNameEqualTo(String value) {
      addCriterion("PROPERTY_NAME =", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameNotEqualTo(String value) {
      addCriterion("PROPERTY_NAME <>", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameGreaterThan(String value) {
      addCriterion("PROPERTY_NAME >", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameGreaterThanOrEqualTo(String value) {
      addCriterion("PROPERTY_NAME >=", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameLessThan(String value) {
      addCriterion("PROPERTY_NAME <", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameLessThanOrEqualTo(String value) {
      addCriterion("PROPERTY_NAME <=", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameLike(String value) {
      addCriterion("PROPERTY_NAME like", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameNotLike(String value) {
      addCriterion("PROPERTY_NAME not like", value, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameIn(List<String> values) {
      addCriterion("PROPERTY_NAME in", values, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameNotIn(List<String> values) {
      addCriterion("PROPERTY_NAME not in", values, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameBetween(String value1, String value2) {
      addCriterion("PROPERTY_NAME between", value1, value2, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyNameNotBetween(String value1, String value2) {
      addCriterion("PROPERTY_NAME not between", value1, value2, "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyValueIsNull() {
      addCriterion("PROPERTY_VALUE is null");
      return (Criteria) this;
    }

    public Criteria andPropertyValueIsNotNull() {
      addCriterion("PROPERTY_VALUE is not null");
      return (Criteria) this;
    }

    public Criteria andPropertyValueEqualTo(String value) {
      addCriterion("PROPERTY_VALUE =", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueNotEqualTo(String value) {
      addCriterion("PROPERTY_VALUE <>", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueGreaterThan(String value) {
      addCriterion("PROPERTY_VALUE >", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueGreaterThanOrEqualTo(String value) {
      addCriterion("PROPERTY_VALUE >=", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueLessThan(String value) {
      addCriterion("PROPERTY_VALUE <", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueLessThanOrEqualTo(String value) {
      addCriterion("PROPERTY_VALUE <=", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueLike(String value) {
      addCriterion("PROPERTY_VALUE like", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueNotLike(String value) {
      addCriterion("PROPERTY_VALUE not like", value, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueIn(List<String> values) {
      addCriterion("PROPERTY_VALUE in", values, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueNotIn(List<String> values) {
      addCriterion("PROPERTY_VALUE not in", values, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueBetween(String value1, String value2) {
      addCriterion("PROPERTY_VALUE between", value1, value2, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyValueNotBetween(String value1, String value2) {
      addCriterion("PROPERTY_VALUE not between", value1, value2, "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeIsNull() {
      addCriterion("PROPERTY_TYPE is null");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeIsNotNull() {
      addCriterion("PROPERTY_TYPE is not null");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeEqualTo(String value) {
      addCriterion("PROPERTY_TYPE =", value, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeNotEqualTo(String value) {
      addCriterion("PROPERTY_TYPE <>", value, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeGreaterThan(String value) {
      addCriterion("PROPERTY_TYPE >", value, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeGreaterThanOrEqualTo(String value) {
      addCriterion("PROPERTY_TYPE >=", value, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeLessThan(String value) {
      addCriterion("PROPERTY_TYPE <", value, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeLessThanOrEqualTo(String value) {
      addCriterion("PROPERTY_TYPE <=", value, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeLike(String value) {
      addCriterion("PROPERTY_TYPE like", value, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeNotLike(String value) {
      addCriterion("PROPERTY_TYPE not like", value, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeIn(List<String> values) {
      addCriterion("PROPERTY_TYPE in", values, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeNotIn(List<String> values) {
      addCriterion("PROPERTY_TYPE not in", values, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeBetween(String value1, String value2) {
      addCriterion("PROPERTY_TYPE between", value1, value2, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeNotBetween(String value1, String value2) {
      addCriterion("PROPERTY_TYPE not between", value1, value2, "propertyType");
      return (Criteria) this;
    }

    public Criteria andPartNoIdIsNull() {
      addCriterion("PART_NO_ID is null");
      return (Criteria) this;
    }

    public Criteria andPartNoIdIsNotNull() {
      addCriterion("PART_NO_ID is not null");
      return (Criteria) this;
    }

    public Criteria andPartNoIdEqualTo(String value) {
      addCriterion("PART_NO_ID =", value, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdNotEqualTo(String value) {
      addCriterion("PART_NO_ID <>", value, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdGreaterThan(String value) {
      addCriterion("PART_NO_ID >", value, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdGreaterThanOrEqualTo(String value) {
      addCriterion("PART_NO_ID >=", value, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdLessThan(String value) {
      addCriterion("PART_NO_ID <", value, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdLessThanOrEqualTo(String value) {
      addCriterion("PART_NO_ID <=", value, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdLike(String value) {
      addCriterion("PART_NO_ID like", value, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdNotLike(String value) {
      addCriterion("PART_NO_ID not like", value, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdIn(List<String> values) {
      addCriterion("PART_NO_ID in", values, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdNotIn(List<String> values) {
      addCriterion("PART_NO_ID not in", values, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdBetween(String value1, String value2) {
      addCriterion("PART_NO_ID between", value1, value2, "partNoId");
      return (Criteria) this;
    }

    public Criteria andPartNoIdNotBetween(String value1, String value2) {
      addCriterion("PART_NO_ID not between", value1, value2, "partNoId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdIsNull() {
      addCriterion("ENUM_VALUE_ID is null");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdIsNotNull() {
      addCriterion("ENUM_VALUE_ID is not null");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdEqualTo(String value) {
      addCriterion("ENUM_VALUE_ID =", value, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdNotEqualTo(String value) {
      addCriterion("ENUM_VALUE_ID <>", value, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdGreaterThan(String value) {
      addCriterion("ENUM_VALUE_ID >", value, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdGreaterThanOrEqualTo(String value) {
      addCriterion("ENUM_VALUE_ID >=", value, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdLessThan(String value) {
      addCriterion("ENUM_VALUE_ID <", value, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdLessThanOrEqualTo(String value) {
      addCriterion("ENUM_VALUE_ID <=", value, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdLike(String value) {
      addCriterion("ENUM_VALUE_ID like", value, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdNotLike(String value) {
      addCriterion("ENUM_VALUE_ID not like", value, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdIn(List<String> values) {
      addCriterion("ENUM_VALUE_ID in", values, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdNotIn(List<String> values) {
      addCriterion("ENUM_VALUE_ID not in", values, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdBetween(String value1, String value2) {
      addCriterion("ENUM_VALUE_ID between", value1, value2, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdNotBetween(String value1, String value2) {
      addCriterion("ENUM_VALUE_ID not between", value1, value2, "enumValueId");
      return (Criteria) this;
    }

    public Criteria andIdLikeInsensitive(String value) {
      addCriterion("upper(ID) like", value.toUpperCase(), "id");
      return (Criteria) this;
    }

    public Criteria andPropertyNameLikeInsensitive(String value) {
      addCriterion("upper(PROPERTY_NAME) like", value.toUpperCase(), "propertyName");
      return (Criteria) this;
    }

    public Criteria andPropertyValueLikeInsensitive(String value) {
      addCriterion("upper(PROPERTY_VALUE) like", value.toUpperCase(), "propertyValue");
      return (Criteria) this;
    }

    public Criteria andPropertyTypeLikeInsensitive(String value) {
      addCriterion("upper(PROPERTY_TYPE) like", value.toUpperCase(), "propertyType");
      return (Criteria) this;
    }

    public Criteria andPartNoIdLikeInsensitive(String value) {
      addCriterion("upper(PART_NO_ID) like", value.toUpperCase(), "partNoId");
      return (Criteria) this;
    }

    public Criteria andEnumValueIdLikeInsensitive(String value) {
      addCriterion("upper(ENUM_VALUE_ID) like", value.toUpperCase(), "enumValueId");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}