
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.csot.recruit.common.webservice.outside.sms;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-10-22T15:52:06.554+08:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "ESB_SMS_SMS_ImportSmsSrv.serviceagent",
                      portName = "ESB_SMS_SMS_ImportSmsSrv",
                      targetNamespace = "http://xmlns.example.com/1435191957135",
                      wsdlLocation = "http://t2eaesbapp01.csot.tcl.com:9014/CoreServices/BusinessServices/Service/ESB_SMS_SMS_ImportSmsSrv/v1.0.0/ESB_SMS_SMS_ImportSmsSrv.serviceagent?wsdl",
                      endpointInterface = "recruit.ESBESBSMSImportSmsSrv")
                      
public class ESBESBSMSImportSmsSrvImpl implements ESBESBSMSImportSmsSrv {

    private static final Logger LOG = Logger.getLogger(ESBESBSMSImportSmsSrvImpl.class.getName());

    /* (non-Javadoc)
     * @see recruit.ESBESBSMSImportSmsSrv#process(recruit.ESBESBSMSImportSmsSrvRequest  payload )*
     */
    public ESBESBSMSImportSmsSrvResponse process(ESBESBSMSImportSmsSrvRequest payload) { 
        LOG.info("Executing operation process");
        System.out.println(payload);
        try {
            ESBESBSMSImportSmsSrvResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
