package com.csot.gm.materialManage.model.original.gmPartDescRuleMap;

import java.io.Serializable;

public class GmPartDescRuleMap implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_DESC_RULE_MAP.ID
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_DESC_RULE_MAP.RULE_KEY_CODE
   *
   * @mbggenerated
   */
  private String ruleKeyCode;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_DESC_RULE_MAP.RULE_MAP_CODE
   *
   * @mbggenerated
   */
  private String ruleMapCode;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_DESC_RULE_MAP.ID
   *
   * @return the value of T_GM_PART_DESC_RULE_MAP.ID
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_DESC_RULE_MAP.ID
   *
   * @param id the value for T_GM_PART_DESC_RULE_MAP.ID
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_DESC_RULE_MAP.RULE_KEY_CODE
   *
   * @return the value of T_GM_PART_DESC_RULE_MAP.RULE_KEY_CODE
   *
   * @mbggenerated
   */
  public String getRuleKeyCode() {
    return ruleKeyCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_DESC_RULE_MAP.RULE_KEY_CODE
   *
   * @param ruleKeyCode the value for T_GM_PART_DESC_RULE_MAP.RULE_KEY_CODE
   *
   * @mbggenerated
   */
  public void setRuleKeyCode(String ruleKeyCode) {
    this.ruleKeyCode = ruleKeyCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_DESC_RULE_MAP.RULE_MAP_CODE
   *
   * @return the value of T_GM_PART_DESC_RULE_MAP.RULE_MAP_CODE
   *
   * @mbggenerated
   */
  public String getRuleMapCode() {
    return ruleMapCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_DESC_RULE_MAP.RULE_MAP_CODE
   *
   * @param ruleMapCode the value for T_GM_PART_DESC_RULE_MAP.RULE_MAP_CODE
   *
   * @mbggenerated
   */
  public void setRuleMapCode(String ruleMapCode) {
    this.ruleMapCode = ruleMapCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    GmPartDescRuleMap other = (GmPartDescRuleMap) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getRuleKeyCode() == null ? other.getRuleKeyCode() == null : this.getRuleKeyCode()
            .equals(other.getRuleKeyCode()))
        && (this.getRuleMapCode() == null ? other.getRuleMapCode() == null : this.getRuleMapCode()
            .equals(other.getRuleMapCode()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PART_DESC_RULE_MAP
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result = prime * result + ((getRuleKeyCode() == null) ? 0 : getRuleKeyCode().hashCode());
    result = prime * result + ((getRuleMapCode() == null) ? 0 : getRuleMapCode().hashCode());
    return result;
  }
}
