package com.csot.gm.esbws.importUpdatePartInfoSrv;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2 2016-01-08T13:29:13.491+08:00 Generated source
 * version: 2.5.2
 * 
 */
@WebServiceClient(name = "ESB_GM_GM_ImportUpdatePartInfoSrv.serviceagent",
    wsdlLocation = "ESB_GM_GM_ImportUpdatePartInfoSrv.wsdl",
    targetNamespace = "http://www.csot.tcl.com/ESB_GM_GM_ImportUpdatePartInfoSrv/1.0")
public class ESBGMGMImportUpdatePartInfoSrvServiceagent extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName(
      "http://www.csot.tcl.com/ESB_GM_GM_ImportUpdatePartInfoSrv/1.0",
      "ESB_GM_GM_ImportUpdatePartInfoSrv.serviceagent");
  public final static QName ESBGMGMImportUpdatePartInfoSrv = new QName(
      "http://www.csot.tcl.com/ESB_GM_GM_ImportUpdatePartInfoSrv/1.0",
      "ESB_GM_GM_ImportUpdatePartInfoSrv");

  static {
    URL url =
        ESBGMGMImportUpdatePartInfoSrvServiceagent.class
            .getResource("ESB_GM_GM_ImportUpdatePartInfoSrv.wsdl");
    if (url == null) {
      java.util.logging.Logger
          .getLogger(ESBGMGMImportUpdatePartInfoSrvServiceagent.class.getName()).log(
              java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
              "ESB_GM_GM_ImportUpdatePartInfoSrv.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public ESBGMGMImportUpdatePartInfoSrvServiceagent(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public ESBGMGMImportUpdatePartInfoSrvServiceagent(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public ESBGMGMImportUpdatePartInfoSrvServiceagent() {
    super(WSDL_LOCATION, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBGMGMImportUpdatePartInfoSrvServiceagent(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBGMGMImportUpdatePartInfoSrvServiceagent(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBGMGMImportUpdatePartInfoSrvServiceagent(URL wsdlLocation, QName serviceName,
      WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns ESBGMGMImportUpdatePartInfoSrv
   */
  @WebEndpoint(name = "ESB_GM_GM_ImportUpdatePartInfoSrv")
  public ESBGMGMImportUpdatePartInfoSrv getESBGMGMImportUpdatePartInfoSrv() {
    return super.getPort(ESBGMGMImportUpdatePartInfoSrv, ESBGMGMImportUpdatePartInfoSrv.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns ESBGMGMImportUpdatePartInfoSrv
   */
  @WebEndpoint(name = "ESB_GM_GM_ImportUpdatePartInfoSrv")
  public ESBGMGMImportUpdatePartInfoSrv getESBGMGMImportUpdatePartInfoSrv(
      WebServiceFeature... features) {
    return super.getPort(ESBGMGMImportUpdatePartInfoSrv, ESBGMGMImportUpdatePartInfoSrv.class,
        features);
  }

}
