package com.csot.gm.materialManage.dao.extension.partClass;

import java.util.List;

import com.csot.gm.materialManage.model.extension.partClass.PartClassExtCriteria;
import com.csot.gm.materialManage.model.original.partClass.PartClass;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PartClassExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_CLASS
   *
   * @mbggenerated
   */
  int countByExample(PartClassExtCriteria example);
  
  List<PartClass> getAllPartClass();
  
  List<PartClass> getByClassDesc(String classDesc);
  
  List<PartClass> getByClassDescAndParentId(@Param("classDesc") String classDesc,
      @Param("pid") String pid);
  
  List<PartClass> getByParentId(String pid);
}