package com.csot.gm.esbws.inquiryPartInfoSrv;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2 2016-01-08T11:46:23.872+08:00 Generated source
 * version: 2.5.2
 * 
 */
@WebServiceClient(name = "ESB_GM_GM_InquiryPartInfoSrv.serviceagent",
    wsdlLocation = "ESB_GM_GM_InquiryPartInfoSrv.wsdl",
    targetNamespace = "http://www.csot.tcl.com/ESB_GM_GM_InquiryPartInfoSrv/1.0")
public class ESBGMGMInquiryPartInfoSrvServiceagent extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName(
      "http://www.csot.tcl.com/ESB_GM_GM_InquiryPartInfoSrv/1.0",
      "ESB_GM_GM_InquiryPartInfoSrv.serviceagent");
  public final static QName ESBGMGMInquiryPartInfoSrv = new QName(
      "http://www.csot.tcl.com/ESB_GM_GM_InquiryPartInfoSrv/1.0", "ESB_GM_GM_InquiryPartInfoSrv");

  static {
    URL url =
        ESBGMGMInquiryPartInfoSrvServiceagent.class
            .getResource("ESB_GM_GM_InquiryPartInfoSrv.wsdl");
    if (url == null) {
      java.util.logging.Logger.getLogger(ESBGMGMInquiryPartInfoSrvServiceagent.class.getName())
          .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
              "ESB_GM_GM_InquiryPartInfoSrv.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public ESBGMGMInquiryPartInfoSrvServiceagent(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public ESBGMGMInquiryPartInfoSrvServiceagent(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public ESBGMGMInquiryPartInfoSrvServiceagent() {
    super(WSDL_LOCATION, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBGMGMInquiryPartInfoSrvServiceagent(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBGMGMInquiryPartInfoSrvServiceagent(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public ESBGMGMInquiryPartInfoSrvServiceagent(URL wsdlLocation, QName serviceName,
      WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns ESBGMGMInquiryPartInfoSrv
   */
  @WebEndpoint(name = "ESB_GM_GM_InquiryPartInfoSrv")
  public ESBGMGMInquiryPartInfoSrv getESBGMGMInquiryPartInfoSrv() {
    return super.getPort(ESBGMGMInquiryPartInfoSrv, ESBGMGMInquiryPartInfoSrv.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns ESBGMGMInquiryPartInfoSrv
   */
  @WebEndpoint(name = "ESB_GM_GM_InquiryPartInfoSrv")
  public ESBGMGMInquiryPartInfoSrv getESBGMGMInquiryPartInfoSrv(WebServiceFeature... features) {
    return super.getPort(ESBGMGMInquiryPartInfoSrv, ESBGMGMInquiryPartInfoSrv.class, features);
  }

}
