package com.csot.gm.materialManage.model.extension.typePartM;

import java.io.Serializable;

public class TypePartMExt implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_TYPE_PART_MAPPING.ID
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_TYPE_PART_MAPPING.PART_TYPE_ID
   *
   * @mbggenerated
   */
  private String partTypeId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_TYPE_PART_MAPPING.PART_ID
   *
   * @mbggenerated
   */
  private String partId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_TYPE_PART_MAPPING.ID
   *
   * @return the value of T_GM_TYPE_PART_MAPPING.ID
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_TYPE_PART_MAPPING.ID
   *
   * @param id the value for T_GM_TYPE_PART_MAPPING.ID
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_TYPE_PART_MAPPING.PART_TYPE_ID
   *
   * @return the value of T_GM_TYPE_PART_MAPPING.PART_TYPE_ID
   *
   * @mbggenerated
   */
  public String getPartTypeId() {
    return partTypeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_TYPE_PART_MAPPING.PART_TYPE_ID
   *
   * @param partTypeId the value for T_GM_TYPE_PART_MAPPING.PART_TYPE_ID
   *
   * @mbggenerated
   */
  public void setPartTypeId(String partTypeId) {
    this.partTypeId = partTypeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_TYPE_PART_MAPPING.PART_ID
   *
   * @return the value of T_GM_TYPE_PART_MAPPING.PART_ID
   *
   * @mbggenerated
   */
  public String getPartId() {
    return partId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_TYPE_PART_MAPPING.PART_ID
   *
   * @param partId the value for T_GM_TYPE_PART_MAPPING.PART_ID
   *
   * @mbggenerated
   */
  public void setPartId(String partId) {
    this.partId = partId;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    TypePartMExt other = (TypePartMExt) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getPartTypeId() == null ? other.getPartTypeId() == null : this.getPartTypeId()
            .equals(other.getPartTypeId()))
        && (this.getPartId() == null ? other.getPartId() == null : this.getPartId().equals(
            other.getPartId()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_TYPE_PART_MAPPING
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result = prime * result + ((getPartTypeId() == null) ? 0 : getPartTypeId().hashCode());
    result = prime * result + ((getPartId() == null) ? 0 : getPartId().hashCode());
    return result;
  }
}
