package com.csot.gm.materialManage.dao.original.partNoRule;

import com.csot.gm.materialManage.model.original.partNoRule.PartNoRule;
import com.csot.gm.materialManage.model.original.partNoRule.PartNoRuleCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PartNoRuleMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  int countByExample(PartNoRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  int deleteByExample(PartNoRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  int insert(PartNoRule record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  int insertSelective(PartNoRule record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  List<PartNoRule> selectByExample(PartNoRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  PartNoRule selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") PartNoRule record,
      @Param("example") PartNoRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") PartNoRule record,
      @Param("example") PartNoRuleCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(PartNoRule record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART_NO_RULE
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(PartNoRule record);
}