package com.csot.gm.materialManage.dao.original.wxmap;

import com.csot.gm.materialManage.model.original.wxmap.WXMap;
import com.csot.gm.materialManage.model.original.wxmap.WXMapCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface WXMapMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int countByExample(WXMapCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int deleteByExample(WXMapCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int insert(WXMap record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int insertSelective(WXMap record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  List<WXMap> selectByExample(WXMapCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  WXMap selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") WXMap record,
      @Param("example") WXMapCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") WXMap record, @Param("example") WXMapCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(WXMap record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_WX_MAPPING
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(WXMap record);
}
