package com.csot.gm.materialManage.dao.original.part;

import com.csot.gm.materialManage.model.original.part.Part;
import com.csot.gm.materialManage.model.original.part.PartCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PartMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  int countByExample(PartCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  int deleteByExample(PartCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  int insert(Part record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  int insertSelective(Part record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  List<Part> selectByExample(PartCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  Part selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
      int
      updateByExampleSelective(@Param("record") Part record, @Param("example") PartCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") Part record, @Param("example") PartCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(Part record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_PART
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Part record);
}