
package com.csot.recruit.common.webservice.applicantInfo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2017-03-14T09:11:18.982+08:00
 * Generated source version: 2.7.12
 * 
 */
public final class ESBHRZPHRZPInquiryApplicantInfoSrv_ESBHRZPHRZPInquiryApplicantInfoSrv_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.plm.csot.kmss.landray.com/", "ESB_HRZP_HRZP_InquiryApplicantInfoSrv.serviceagent");

    private ESBHRZPHRZPInquiryApplicantInfoSrv_ESBHRZPHRZPInquiryApplicantInfoSrv_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ESBHRZPHRZPInquiryApplicantInfoSrvServiceagent.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ESBHRZPHRZPInquiryApplicantInfoSrvServiceagent ss = new ESBHRZPHRZPInquiryApplicantInfoSrvServiceagent(wsdlURL, SERVICE_NAME);
        ESBHRZPHRZPInquiryApplicantInfoSrv port = ss.getESBHRZPHRZPInquiryApplicantInfoSrv();  
        
        {
        System.out.println("Invoking process...");
        ESBHRZPHRZPInquiryApplicantInfoSrvRequest _process_payload = new ESBHRZPHRZPInquiryApplicantInfoSrvRequest();
        _process_payload.setAPPLICATIONCODE("asdfasf");
        ESBHRZPHRZPInquiryApplicantInfoSrvResponse _process__return = port.process(_process_payload);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
