package com.csot.gm.materialManage.dao.original.systemNotice;

import com.csot.gm.materialManage.model.original.systemNotice.SystemNotice;
import com.csot.gm.materialManage.model.original.systemNotice.SystemNoticeCriteria;
import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface SystemNoticeMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int countByExample(SystemNoticeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int deleteByExample(SystemNoticeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int insert(SystemNotice record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int insertSelective(SystemNotice record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  List<SystemNotice> selectByExampleWithBLOBs(SystemNoticeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  List<SystemNotice> selectByExample(SystemNoticeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  SystemNotice selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") SystemNotice record, @Param("example") SystemNoticeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int updateByExampleWithBLOBs(@Param("record") SystemNotice record, @Param("example") SystemNoticeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") SystemNotice record, @Param("example") SystemNoticeCriteria example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(SystemNotice record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int updateByPrimaryKeyWithBLOBs(SystemNotice record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table T_GM_SYSTEM_NOTICE
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(SystemNotice record);
}