package com.csot.gm.materialManage.dao.original.propertyValue;

import com.csot.gm.materialManage.model.original.propertyValue.PropertyValue;
import com.csot.gm.materialManage.model.original.propertyValue.PropertyValueCriteria;

import java.util.List;
import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PropertyValueMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int countByExample(PropertyValueCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int deleteByExample(PropertyValueCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int insert(PropertyValue record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int insertSelective(PropertyValue record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  List<PropertyValue> selectByExample(PropertyValueCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  PropertyValue selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") PropertyValue record,
      @Param("example") PropertyValueCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int updateByExample(@Param("record") PropertyValue record,
      @Param("example") PropertyValueCriteria example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(PropertyValue record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(PropertyValue record);
}
