package com.csot.gm.materialManage.dao.extension.propertyValue;

import java.util.List;

import com.csot.gm.materialManage.model.extension.propertyValue.PropertyValueExt;
import com.csot.gm.materialManage.model.extension.propertyValue.PropertyValueExtCriteria;

import org.amberframework.core.mybatis.dao.MyBatisBaseMapper;
import org.apache.ibatis.annotations.Param;

public interface PropertyValueExtMapper extends MyBatisBaseMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTY_VALUE
   *
   * @mbggenerated
   */
  int countByExample(PropertyValueExtCriteria example);

  /**
   * 此处查出的属性只有作唯一性判断的属性，即property_type='Y'
   * 
   * @param partNoId
   * @return
   */
  List<PropertyValueExt> selectPropertyValueByPartNo(String partNoId);

  /**
   * 此处查出所有属性值
   * 
   * @param partNoId
   * @return
   */
  List<PropertyValueExt> selectPropertyValueByPartNoId(String partNoId);

  int deleteByPartNoId(String partNoId);

  /**
   * 此处查出对应的料号的属性的属性值
   * 
   * @param partNoId, propertyName
   * @return
   */
  List<PropertyValueExt> selectPropertyValueByPartNoIdAndPropertyName(
      @Param("partNoId") String partNoId, @Param("propertyName") String propertyName);

  List<PropertyValueExt> selectPropertyValueByLikePropertyValue(String propertyValue);

  List<PropertyValueExt> selectPropertyValueByPropertyNameLikePropertyValue(
      @Param("propertyName") String propertyName, @Param("propertyValue") String propertyValue);

  // 通过属性名和属性值查询料号属性
  List<PropertyValueExt> selectProValueByPropertyNameAndPropertyValue(
      @Param("propertyName") String propertyName, @Param("propertyValue") String propertyValue);

}
