package com.csot.recruit.common.webservice.outside.postingExtra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-10-15T09:36:59.321+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webservice.plm.csot.kmss.landray.com/", name = "ESB_GYD_GYD_InquiryPostingExtraSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ESBGYDGYDInquiryPostingExtraSrv {

    @WebResult(name = "ESB_GYD_GYD_InquiryPostingExtraSrvResponse", targetNamespace = "http://www.csot.tcl.com/ESB_GYD_GYD_InquiryPostingExtraSrv/1.0", partName = "payload")
    @WebMethod(action = "/ESB_GYD_GYD_InquiryPostingExtraSrv/v1/process")
    public ESBGYDGYDInquiryPostingExtraSrvResponse process(
        @WebParam(partName = "payload", name = "ESB_GYD_GYD_InquiryPostingExtraSrvRequest", targetNamespace = "http://www.csot.tcl.com/ESB_GYD_GYD_InquiryPostingExtraSrv/1.0")
        ESBGYDGYDInquiryPostingExtraSrvRequest payload
    );
}
