package com.csot.gm.materialManage.model.original.partNo;

import java.io.Serializable;
import java.util.Date;

public class PartNo implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.ID
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.PART_NO
   *
   * @mbggenerated
   */
  private String partNo;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.PART_NAME
   *
   * @mbggenerated
   */
  private String partName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.CN_DESC
   *
   * @mbggenerated
   */
  private String cnDesc;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.EN_DESC
   *
   * @mbggenerated
   */
  private String enDesc;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.CREATE_CODE
   *
   * @mbggenerated
   */
  private String createCode;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.CREATE_TIME
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.PART_NO_STATUS
   *
   * @mbggenerated
   */
  private String partNoStatus;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.PART_ID
   *
   * @mbggenerated
   */
  private String partId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.HASH_CODE
   *
   * @mbggenerated
   */
  private String hashCode;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.PART_NO_UID
   *
   * @mbggenerated
   */
  private String partNoUid;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.CREATE_NAME
   *
   * @mbggenerated
   */
  private String createName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.PLANT
   *
   * @mbggenerated
   */
  private String plant;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.DEPARTMENT
   *
   * @mbggenerated
   */
  private String department;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.TELEPHONE
   *
   * @mbggenerated
   */
  private String telephone;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_NO.PART_TYPE
   *
   * @mbggenerated
   */
  private String partType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_PART_NO
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.ID
   *
   * @return the value of T_GM_PART_NO.ID
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.ID
   *
   * @param id the value for T_GM_PART_NO.ID
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.PART_NO
   *
   * @return the value of T_GM_PART_NO.PART_NO
   *
   * @mbggenerated
   */
  public String getPartNo() {
    return partNo;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.PART_NO
   *
   * @param partNo the value for T_GM_PART_NO.PART_NO
   *
   * @mbggenerated
   */
  public void setPartNo(String partNo) {
    this.partNo = partNo;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.PART_NAME
   *
   * @return the value of T_GM_PART_NO.PART_NAME
   *
   * @mbggenerated
   */
  public String getPartName() {
    return partName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.PART_NAME
   *
   * @param partName the value for T_GM_PART_NO.PART_NAME
   *
   * @mbggenerated
   */
  public void setPartName(String partName) {
    this.partName = partName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.CN_DESC
   *
   * @return the value of T_GM_PART_NO.CN_DESC
   *
   * @mbggenerated
   */
  public String getCnDesc() {
    return cnDesc;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.CN_DESC
   *
   * @param cnDesc the value for T_GM_PART_NO.CN_DESC
   *
   * @mbggenerated
   */
  public void setCnDesc(String cnDesc) {
    this.cnDesc = cnDesc;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.EN_DESC
   *
   * @return the value of T_GM_PART_NO.EN_DESC
   *
   * @mbggenerated
   */
  public String getEnDesc() {
    return enDesc;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.EN_DESC
   *
   * @param enDesc the value for T_GM_PART_NO.EN_DESC
   *
   * @mbggenerated
   */
  public void setEnDesc(String enDesc) {
    this.enDesc = enDesc;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.CREATE_CODE
   *
   * @return the value of T_GM_PART_NO.CREATE_CODE
   *
   * @mbggenerated
   */
  public String getCreateCode() {
    return createCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.CREATE_CODE
   *
   * @param createCode the value for T_GM_PART_NO.CREATE_CODE
   *
   * @mbggenerated
   */
  public void setCreateCode(String createCode) {
    this.createCode = createCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.CREATE_TIME
   *
   * @return the value of T_GM_PART_NO.CREATE_TIME
   *
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.CREATE_TIME
   *
   * @param createTime the value for T_GM_PART_NO.CREATE_TIME
   *
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.PART_NO_STATUS
   *
   * @return the value of T_GM_PART_NO.PART_NO_STATUS
   *
   * @mbggenerated
   */
  public String getPartNoStatus() {
    return partNoStatus;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.PART_NO_STATUS
   *
   * @param partNoStatus the value for T_GM_PART_NO.PART_NO_STATUS
   *
   * @mbggenerated
   */
  public void setPartNoStatus(String partNoStatus) {
    this.partNoStatus = partNoStatus;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.PART_ID
   *
   * @return the value of T_GM_PART_NO.PART_ID
   *
   * @mbggenerated
   */
  public String getPartId() {
    return partId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.PART_ID
   *
   * @param partId the value for T_GM_PART_NO.PART_ID
   *
   * @mbggenerated
   */
  public void setPartId(String partId) {
    this.partId = partId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.HASH_CODE
   *
   * @return the value of T_GM_PART_NO.HASH_CODE
   *
   * @mbggenerated
   */
  public String getHashCode() {
    return hashCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.HASH_CODE
   *
   * @param hashCode the value for T_GM_PART_NO.HASH_CODE
   *
   * @mbggenerated
   */
  public void setHashCode(String hashCode) {
    this.hashCode = hashCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.PART_NO_UID
   *
   * @return the value of T_GM_PART_NO.PART_NO_UID
   *
   * @mbggenerated
   */
  public String getPartNoUid() {
    return partNoUid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.PART_NO_UID
   *
   * @param partNoUid the value for T_GM_PART_NO.PART_NO_UID
   *
   * @mbggenerated
   */
  public void setPartNoUid(String partNoUid) {
    this.partNoUid = partNoUid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.CREATE_NAME
   *
   * @return the value of T_GM_PART_NO.CREATE_NAME
   *
   * @mbggenerated
   */
  public String getCreateName() {
    return createName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.CREATE_NAME
   *
   * @param createName the value for T_GM_PART_NO.CREATE_NAME
   *
   * @mbggenerated
   */
  public void setCreateName(String createName) {
    this.createName = createName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.PLANT
   *
   * @return the value of T_GM_PART_NO.PLANT
   *
   * @mbggenerated
   */
  public String getPlant() {
    return plant;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.PLANT
   *
   * @param plant the value for T_GM_PART_NO.PLANT
   *
   * @mbggenerated
   */
  public void setPlant(String plant) {
    this.plant = plant;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.DEPARTMENT
   *
   * @return the value of T_GM_PART_NO.DEPARTMENT
   *
   * @mbggenerated
   */
  public String getDepartment() {
    return department;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.DEPARTMENT
   *
   * @param department the value for T_GM_PART_NO.DEPARTMENT
   *
   * @mbggenerated
   */
  public void setDepartment(String department) {
    this.department = department;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.TELEPHONE
   *
   * @return the value of T_GM_PART_NO.TELEPHONE
   *
   * @mbggenerated
   */
  public String getTelephone() {
    return telephone;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.TELEPHONE
   *
   * @param telephone the value for T_GM_PART_NO.TELEPHONE
   *
   * @mbggenerated
   */
  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_NO.PART_TYPE
   *
   * @return the value of T_GM_PART_NO.PART_TYPE
   *
   * @mbggenerated
   */
  public String getPartType() {
    return partType;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_NO.PART_TYPE
   *
   * @param partType the value for T_GM_PART_NO.PART_TYPE
   *
   * @mbggenerated
   */
  public void setPartType(String partType) {
    this.partType = partType;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PART_NO
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    PartNo other = (PartNo) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getPartNo() == null ? other.getPartNo() == null : this.getPartNo().equals(
            other.getPartNo()))
        && (this.getPartName() == null ? other.getPartName() == null : this.getPartName().equals(
            other.getPartName()))
        && (this.getCnDesc() == null ? other.getCnDesc() == null : this.getCnDesc().equals(
            other.getCnDesc()))
        && (this.getEnDesc() == null ? other.getEnDesc() == null : this.getEnDesc().equals(
            other.getEnDesc()))
        && (this.getCreateCode() == null ? other.getCreateCode() == null : this.getCreateCode()
            .equals(other.getCreateCode()))
        && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime()
            .equals(other.getCreateTime()))
        && (this.getPartNoStatus() == null ? other.getPartNoStatus() == null : this
            .getPartNoStatus().equals(other.getPartNoStatus()))
        && (this.getPartId() == null ? other.getPartId() == null : this.getPartId().equals(
            other.getPartId()))
        && (this.getHashCode() == null ? other.getHashCode() == null : this.getHashCode().equals(
            other.getHashCode()))
        && (this.getPartNoUid() == null ? other.getPartNoUid() == null : this.getPartNoUid()
            .equals(other.getPartNoUid()))
        && (this.getCreateName() == null ? other.getCreateName() == null : this.getCreateName()
            .equals(other.getCreateName()))
        && (this.getPlant() == null ? other.getPlant() == null : this.getPlant().equals(
            other.getPlant()))
        && (this.getDepartment() == null ? other.getDepartment() == null : this.getDepartment()
            .equals(other.getDepartment()))
        && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone()
            .equals(other.getTelephone()))
        && (this.getPartType() == null ? other.getPartType() == null : this.getPartType().equals(
            other.getPartType()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PART_NO
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result = prime * result + ((getPartNo() == null) ? 0 : getPartNo().hashCode());
    result = prime * result + ((getPartName() == null) ? 0 : getPartName().hashCode());
    result = prime * result + ((getCnDesc() == null) ? 0 : getCnDesc().hashCode());
    result = prime * result + ((getEnDesc() == null) ? 0 : getEnDesc().hashCode());
    result = prime * result + ((getCreateCode() == null) ? 0 : getCreateCode().hashCode());
    result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
    result = prime * result + ((getPartNoStatus() == null) ? 0 : getPartNoStatus().hashCode());
    result = prime * result + ((getPartId() == null) ? 0 : getPartId().hashCode());
    result = prime * result + ((getHashCode() == null) ? 0 : getHashCode().hashCode());
    result = prime * result + ((getPartNoUid() == null) ? 0 : getPartNoUid().hashCode());
    result = prime * result + ((getCreateName() == null) ? 0 : getCreateName().hashCode());
    result = prime * result + ((getPlant() == null) ? 0 : getPlant().hashCode());
    result = prime * result + ((getDepartment() == null) ? 0 : getDepartment().hashCode());
    result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
    result = prime * result + ((getPartType() == null) ? 0 : getPartType().hashCode());
    return result;
  }
}
