package com.csot.gm.materialManage.model.extension.gmPartDescRule;

import java.io.Serializable;
import java.math.BigDecimal;

public class GmPartDescRuleExt implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_DESC_RULE.ID
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_DESC_RULE.RULE_KEY_CODE
   *
   * @mbggenerated
   */
  private String ruleKeyCode;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_DESC_RULE.RULE_PROPERTY_NAME
   *
   * @mbggenerated
   */
  private String rulePropertyName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_DESC_RULE.RULE_PROPERTY_INDEX
   *
   * @mbggenerated
   */
  private BigDecimal rulePropertyIndex;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PART_DESC_RULE.CONNECT_SYMBOL
   *
   * @mbggenerated
   */
  private String connectSymbol;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_DESC_RULE.ID
   *
   * @return the value of T_GM_PART_DESC_RULE.ID
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_DESC_RULE.ID
   *
   * @param id the value for T_GM_PART_DESC_RULE.ID
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_DESC_RULE.RULE_KEY_CODE
   *
   * @return the value of T_GM_PART_DESC_RULE.RULE_KEY_CODE
   *
   * @mbggenerated
   */
  public String getRuleKeyCode() {
    return ruleKeyCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_DESC_RULE.RULE_KEY_CODE
   *
   * @param ruleKeyCode the value for T_GM_PART_DESC_RULE.RULE_KEY_CODE
   *
   * @mbggenerated
   */
  public void setRuleKeyCode(String ruleKeyCode) {
    this.ruleKeyCode = ruleKeyCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_DESC_RULE.RULE_PROPERTY_NAME
   *
   * @return the value of T_GM_PART_DESC_RULE.RULE_PROPERTY_NAME
   *
   * @mbggenerated
   */
  public String getRulePropertyName() {
    return rulePropertyName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_DESC_RULE.RULE_PROPERTY_NAME
   *
   * @param rulePropertyName the value for T_GM_PART_DESC_RULE.RULE_PROPERTY_NAME
   *
   * @mbggenerated
   */
  public void setRulePropertyName(String rulePropertyName) {
    this.rulePropertyName = rulePropertyName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_DESC_RULE.RULE_PROPERTY_INDEX
   *
   * @return the value of T_GM_PART_DESC_RULE.RULE_PROPERTY_INDEX
   *
   * @mbggenerated
   */
  public BigDecimal getRulePropertyIndex() {
    return rulePropertyIndex;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_DESC_RULE.RULE_PROPERTY_INDEX
   *
   * @param rulePropertyIndex the value for T_GM_PART_DESC_RULE.RULE_PROPERTY_INDEX
   *
   * @mbggenerated
   */
  public void setRulePropertyIndex(BigDecimal rulePropertyIndex) {
    this.rulePropertyIndex = rulePropertyIndex;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PART_DESC_RULE.CONNECT_SYMBOL
   *
   * @return the value of T_GM_PART_DESC_RULE.CONNECT_SYMBOL
   *
   * @mbggenerated
   */
  public String getConnectSymbol() {
    return connectSymbol;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PART_DESC_RULE.CONNECT_SYMBOL
   *
   * @param connectSymbol the value for T_GM_PART_DESC_RULE.CONNECT_SYMBOL
   *
   * @mbggenerated
   */
  public void setConnectSymbol(String connectSymbol) {
    this.connectSymbol = connectSymbol;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    GmPartDescRuleExt other = (GmPartDescRuleExt) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getRuleKeyCode() == null ? other.getRuleKeyCode() == null : this.getRuleKeyCode()
            .equals(other.getRuleKeyCode()))
        && (this.getRulePropertyName() == null ? other.getRulePropertyName() == null : this
            .getRulePropertyName().equals(other.getRulePropertyName()))
        && (this.getRulePropertyIndex() == null ? other.getRulePropertyIndex() == null : this
            .getRulePropertyIndex().equals(other.getRulePropertyIndex()))
        && (this.getConnectSymbol() == null ? other.getConnectSymbol() == null : this
            .getConnectSymbol().equals(other.getConnectSymbol()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PART_DESC_RULE
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result = prime * result + ((getRuleKeyCode() == null) ? 0 : getRuleKeyCode().hashCode());
    result =
        prime * result + ((getRulePropertyName() == null) ? 0 : getRulePropertyName().hashCode());
    result =
        prime * result + ((getRulePropertyIndex() == null) ? 0 : getRulePropertyIndex().hashCode());
    result = prime * result + ((getConnectSymbol() == null) ? 0 : getConnectSymbol().hashCode());
    return result;
  }
}
