package com.csot.gm.materialManage.model.original.propertiesM;

import java.io.Serializable;

public class PropertiesM implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PROPERTIES_MAPPING.ID
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PROPERTIES_MAPPING.PROPERTY_ID
   *
   * @mbggenerated
   */
  private String propertyId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * T_GM_PROPERTIES_MAPPING.ENUM_ID
   *
   * @mbggenerated
   */
  private String enumId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PROPERTIES_MAPPING.ID
   *
   * @return the value of T_GM_PROPERTIES_MAPPING.ID
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PROPERTIES_MAPPING.ID
   *
   * @param id the value for T_GM_PROPERTIES_MAPPING.ID
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PROPERTIES_MAPPING.PROPERTY_ID
   *
   * @return the value of T_GM_PROPERTIES_MAPPING.PROPERTY_ID
   *
   * @mbggenerated
   */
  public String getPropertyId() {
    return propertyId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PROPERTIES_MAPPING.PROPERTY_ID
   *
   * @param propertyId the value for T_GM_PROPERTIES_MAPPING.PROPERTY_ID
   *
   * @mbggenerated
   */
  public void setPropertyId(String propertyId) {
    this.propertyId = propertyId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column T_GM_PROPERTIES_MAPPING.ENUM_ID
   *
   * @return the value of T_GM_PROPERTIES_MAPPING.ENUM_ID
   *
   * @mbggenerated
   */
  public String getEnumId() {
    return enumId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column T_GM_PROPERTIES_MAPPING.ENUM_ID
   *
   * @param enumId the value for T_GM_PROPERTIES_MAPPING.ENUM_ID
   *
   * @mbggenerated
   */
  public void setEnumId(String enumId) {
    this.enumId = enumId;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    PropertiesM other = (PropertiesM) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getPropertyId() == null ? other.getPropertyId() == null : this.getPropertyId()
            .equals(other.getPropertyId()))
        && (this.getEnumId() == null ? other.getEnumId() == null : this.getEnumId().equals(
            other.getEnumId()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * T_GM_PROPERTIES_MAPPING
   *
   * @mbggenerated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result = prime * result + ((getPropertyId() == null) ? 0 : getPropertyId().hashCode());
    result = prime * result + ((getEnumId() == null) ? 0 : getEnumId().hashCode());
    return result;
  }
}
